POST http://127.0.0.1:8002/doctors/register/
Content-Type: application/json

{
    "first_name":"Levin",
    "last_name":"Warren",
    "surname":"Sanders",
    "email":"levsanders@gmail.com",
    "password":"Doctor@@1",
    "phone":"254700000002",
    "id_number":"11111113",
    "specialization":"efd497f2-13e7-49cd-9310-4cc8966b8761",
    "profile": ""
}

###
POST http://127.0.0.1:8002/doctors/login/
Content-Type: application/json

{
    "email":"kariukialvin@gmail.com",
    "password":"Doctor@@1"
}

###
POST  http://127.0.0.1:8002/doctors/specializations/
Authorization: Token eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQzODcyNzI2LCJpYXQiOjE3NDM4NjkxMjYsImp0aSI6IjEwYzViYzQzNTAzNDQzOWRhMGRhY2JlZTZiNTY2MmJjIiwidXNlcl9pZCI6IjBmOGI0NGZjLWU3Y2ItNDAwZi04ZDVkLTI1ZTIwYTUxYzI3ZCIsImlzX3N1cGVydXNlciI6ZmFsc2UsImlzX3N0YWZmIjpmYWxzZSwiaXNfYWN0aXZlIjp0cnVlLCJkb2N0b3JfaWQiOiIwZjhiNDRmYy1lN2NiLTQwMGYtOGQ1ZC0yNWUyMGE1MWMyN2QiLCJpc3MiOiJkb2N0b3Jfc2VydmljZSIsImF1ZCI6WyJwYXRpZW50X3NlcnZpY2UiLCJtZWRpY2FsX3JlY29yZHNfc2VydmljZSIsImFwcG9pbnRtZW50X3NlcnZpY2UiXX0.otzDMtus_RDPoXtwzqT1vq3ybw7D8kmITG42cjeRDeI3VMn_qvlGwHNkr8Pd96AkF0HFyrS5Cq8hymA2Lcm5n2_TV-9xAbnqdTUOzEZFmqq5ebAfbyk1iH8gHXI8o2whqmefiY8p9i3wGzOw27mjHpZllTwkS2AA6JP6cC5ENq19WNaSqJ1iz37FVl8KIfdPA0OMhqDOLQstG6lJXlLX0HZLyIWGX0DfcVxJQVm7kcJLhnUSxSbLaRNWN3YlndLgUsy35aN3XrEfFQa8kFDxY3M7UJxNUdGLDH_s0AP5AP-w4C2HkbU2yYpsRSDx-FRVqRv17PxAcidyfsHbYoo8_g
Content-Type: application/json

{
    "title":"Neurology",
    "description":""
}

###
GET  http://127.0.0.1:8002/doctors/specializations/
Authorization: Token eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ1MTU4ODI5LCJpYXQiOjE3NDUxNTUyMjksImp0aSI6IjEwZjk5ZGFhMjg5ZjQ5ZDNiZTlkYjhlZmU3MzRiNWJkIiwidXNlcl9pZCI6IjE2MTI2YzQ1LTIwNDktNDU4Mi05NTRhLTA0MTc1MjJkNTRiMSIsImlzX3N1cGVydXNlciI6ZmFsc2UsImlzX3N0YWZmIjpmYWxzZSwiaXNfYWN0aXZlIjp0cnVlLCJpc3MiOiJkb2N0b3Jfc2VydmljZSIsImF1ZCI6WyJwYXRpZW50X3NlcnZpY2UiLCJtZWRpY2FsX3JlY29yZHNfc2VydmljZSIsImFwcG9pbnRtZW50X3NlcnZpY2UiXSwicm9sZSI6ImRvY3RvciJ9.lToAEP4pLfmtxV9H9SsePDNyswefd3cVXoeRzdh30EedXxxLuAIW_viWmNu2yAwP0zZAnBBHLVHt6fP2_UrB0EUr4XikdCal6RphrvKQ9bk6WLtTMwgriRnBtx-cepzLHrD_wfMzZkYzdwr9TklPi7AwA-D1fGQDLdV1US9hr1Ij_VflUchVWt7ywR3KugrZkDhu_9Ho2Xq9pb_Mgoq5qnfq4D-jPYB6vaVmcOfceLFgN_B7yndbaZYLOSGmRv0BX1VtnDayqR1Unc7oGUwMP-M19bu987jcaet1HyfVYXFpcyzdWAteVcUdCHIG2jlryPaZXPX_th2SH4ij9rB1tw

###
GET  http://127.0.0.1:8002/doctors/
Authorization: Token eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ1MTU4ODI5LCJpYXQiOjE3NDUxNTUyMjksImp0aSI6IjEwZjk5ZGFhMjg5ZjQ5ZDNiZTlkYjhlZmU3MzRiNWJkIiwidXNlcl9pZCI6IjE2MTI2YzQ1LTIwNDktNDU4Mi05NTRhLTA0MTc1MjJkNTRiMSIsImlzX3N1cGVydXNlciI6ZmFsc2UsImlzX3N0YWZmIjpmYWxzZSwiaXNfYWN0aXZlIjp0cnVlLCJpc3MiOiJkb2N0b3Jfc2VydmljZSIsImF1ZCI6WyJwYXRpZW50X3NlcnZpY2UiLCJtZWRpY2FsX3JlY29yZHNfc2VydmljZSIsImFwcG9pbnRtZW50X3NlcnZpY2UiXSwicm9sZSI6ImRvY3RvciJ9.lToAEP4pLfmtxV9H9SsePDNyswefd3cVXoeRzdh30EedXxxLuAIW_viWmNu2yAwP0zZAnBBHLVHt6fP2_UrB0EUr4XikdCal6RphrvKQ9bk6WLtTMwgriRnBtx-cepzLHrD_wfMzZkYzdwr9TklPi7AwA-D1fGQDLdV1US9hr1Ij_VflUchVWt7ywR3KugrZkDhu_9Ho2Xq9pb_Mgoq5qnfq4D-jPYB6vaVmcOfceLFgN_B7yndbaZYLOSGmRv0BX1VtnDayqR1Unc7oGUwMP-M19bu987jcaet1HyfVYXFpcyzdWAteVcUdCHIG2jlryPaZXPX_th2SH4ij9rB1tw

###
GET  http://127.0.0.1:8000/doctors/a8a00fb4-8349-4fe3-b5e5-f736552b136e/
Authorization: Token eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQzODcyNzI2LCJpYXQiOjE3NDM4NjkxMjYsImp0aSI6IjEwYzViYzQzNTAzNDQzOWRhMGRhY2JlZTZiNTY2MmJjIiwidXNlcl9pZCI6IjBmOGI0NGZjLWU3Y2ItNDAwZi04ZDVkLTI1ZTIwYTUxYzI3ZCIsImlzX3N1cGVydXNlciI6ZmFsc2UsImlzX3N0YWZmIjpmYWxzZSwiaXNfYWN0aXZlIjp0cnVlLCJkb2N0b3JfaWQiOiIwZjhiNDRmYy1lN2NiLTQwMGYtOGQ1ZC0yNWUyMGE1MWMyN2QiLCJpc3MiOiJkb2N0b3Jfc2VydmljZSIsImF1ZCI6WyJwYXRpZW50X3NlcnZpY2UiLCJtZWRpY2FsX3JlY29yZHNfc2VydmljZSIsImFwcG9pbnRtZW50X3NlcnZpY2UiXX0.otzDMtus_RDPoXtwzqT1vq3ybw7D8kmITG42cjeRDeI3VMn_qvlGwHNkr8Pd96AkF0HFyrS5Cq8hymA2Lcm5n2_TV-9xAbnqdTUOzEZFmqq5ebAfbyk1iH8gHXI8o2whqmefiY8p9i3wGzOw27mjHpZllTwkS2AA6JP6cC5ENq19WNaSqJ1iz37FVl8KIfdPA0OMhqDOLQstG6lJXlLX0HZLyIWGX0DfcVxJQVm7kcJLhnUSxSbLaRNWN3YlndLgUsy35aN3XrEfFQa8kFDxY3M7UJxNUdGLDH_s0AP5AP-w4C2HkbU2yYpsRSDx-FRVqRv17PxAcidyfsHbYoo8_g

###
PUT  http://127.0.0.1:8000/doctors/d1554f79-d9c9-4774-a4af-b0a608e3c9f8/
Authorization: Token eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQzODcyNzI2LCJpYXQiOjE3NDM4NjkxMjYsImp0aSI6IjEwYzViYzQzNTAzNDQzOWRhMGRhY2JlZTZiNTY2MmJjIiwidXNlcl9pZCI6IjBmOGI0NGZjLWU3Y2ItNDAwZi04ZDVkLTI1ZTIwYTUxYzI3ZCIsImlzX3N1cGVydXNlciI6ZmFsc2UsImlzX3N0YWZmIjpmYWxzZSwiaXNfYWN0aXZlIjp0cnVlLCJkb2N0b3JfaWQiOiIwZjhiNDRmYy1lN2NiLTQwMGYtOGQ1ZC0yNWUyMGE1MWMyN2QiLCJpc3MiOiJkb2N0b3Jfc2VydmljZSIsImF1ZCI6WyJwYXRpZW50X3NlcnZpY2UiLCJtZWRpY2FsX3JlY29yZHNfc2VydmljZSIsImFwcG9pbnRtZW50X3NlcnZpY2UiXX0.otzDMtus_RDPoXtwzqT1vq3ybw7D8kmITG42cjeRDeI3VMn_qvlGwHNkr8Pd96AkF0HFyrS5Cq8hymA2Lcm5n2_TV-9xAbnqdTUOzEZFmqq5ebAfbyk1iH8gHXI8o2whqmefiY8p9i3wGzOw27mjHpZllTwkS2AA6JP6cC5ENq19WNaSqJ1iz37FVl8KIfdPA0OMhqDOLQstG6lJXlLX0HZLyIWGX0DfcVxJQVm7kcJLhnUSxSbLaRNWN3YlndLgUsy35aN3XrEfFQa8kFDxY3M7UJxNUdGLDH_s0AP5AP-w4C2HkbU2yYpsRSDx-FRVqRv17PxAcidyfsHbYoo8_g
Content-Type: application/json

{
  "id": "d1554f79-d9c9-4774-a4af-b0a608e3c9f8",
  "first_name": "SurtestTest",
  "last_name": "Doctor",
  "surname": "Second",
  "email": "std@gmail.com",
  "phone": "254711111111",
  "specialization": "697f87d0-e497-41c0-8788-49916e6f3d25",
  "profile": "default",
  "id_number": "12345679"
}

###
DELETE  http://127.0.0.1:8002/doctors/d51cfe79-61db-4f6e-bba1-56bb02c90b29/
Authorization: Token eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ0ODM2NDUwLCJpYXQiOjE3NDQ4MzI4NTAsImp0aSI6IjY3Mjg1Y2IzMjYxOTRhN2Q5Nzk0Y2JhZTNkNTU1ZWUzIiwidXNlcl9pZCI6IjcxNTQyNGY4LTJjOWEtNDVjYS1hMmU4LTcxNjgyNWExYmU0ZiIsImlzX3N1cGVydXNlciI6ZmFsc2UsImlzX3N0YWZmIjpmYWxzZSwiaXNfYWN0aXZlIjp0cnVlLCJpc3MiOiJkb2N0b3Jfc2VydmljZSIsImF1ZCI6WyJwYXRpZW50X3NlcnZpY2UiLCJtZWRpY2FsX3JlY29yZHNfc2VydmljZSIsImFwcG9pbnRtZW50X3NlcnZpY2UiXSwicm9sZSI6ImRvY3RvciJ9.P1f7rY72a3fNGo4-avLx4B8JygDeiGY2WUdADYyCbyVtLjbAMdXmxccb21GmuPkyDZY74M_2cfP41A2ChLg8v9_9hBZfs_OOYnTr-Df4VW7ZG_3wsAU2raTl_EmAhiaALtJI-PZtyhJq-6ieMmqPv1QuYg9Z2eaNuMbLu2mHT6k4iMiOeKK9pnN_YK6YPqsxaH3O0sKlWDSwxbajVic-gfBOa2-dvF0cW_YhLnpR2oeu7HNeQIHNMRHeZM5yBxOYMPm8P3nHiZZWTes891yv82Ck5P31yO2lNJarZ9CT3bCN-EG7djCll7ZcLnoB1XuSFYrQkYHn3LzQW5Sh2AJzGw

###
PUT  http://127.0.0.1:8000/doctors/me/password/
Authorization: Token eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQzODc0NzIwLCJpYXQiOjE3NDM4NzExMjAsImp0aSI6IjU0YzY2OWZhM2RlNjQ0NGFhZDVkOTQwNTUwM2ZlYThlIiwidXNlcl9pZCI6IjBmOGI0NGZjLWU3Y2ItNDAwZi04ZDVkLTI1ZTIwYTUxYzI3ZCIsImlzX3N1cGVydXNlciI6ZmFsc2UsImlzX3N0YWZmIjpmYWxzZSwiaXNfYWN0aXZlIjp0cnVlLCJkb2N0b3JfaWQiOiIwZjhiNDRmYy1lN2NiLTQwMGYtOGQ1ZC0yNWUyMGE1MWMyN2QiLCJpc3MiOiJkb2N0b3Jfc2VydmljZSIsImF1ZCI6WyJwYXRpZW50X3NlcnZpY2UiLCJtZWRpY2FsX3JlY29yZHNfc2VydmljZSIsImFwcG9pbnRtZW50X3NlcnZpY2UiXX0.CSA8Rm-UT14c6TVjit5HRuMqg26g9CIZGMXfZ-qpQgIWolaeJxpaHyJIvEnqxNFq21PSQpJ0GWdpsTPSl-6xfGQVfCBY_lRWCmWrugJ8l5CBUEZj04IBuT33bNqrrZy-u820BRS9xnGbL5rUWhJmkapgKPPC_vVigem7eJ1gA18NDPOPz7IqhR9wlO-FNmI_JiExRGMASbIZRWtBX6WscVGF5AiyD4C1DDYGy7-dSSSddqYKosu7Hd3wd7_f7mOxvfm9RmgCHGI4ZHb7WHAKKkbS-HsYvYlV4UPl0AU3Xhi_-Zn5S-HW8AsOWiqrrowRplLrAgZH2Ee8myQflL2zig
Content-Type: application/json

{
    "old_password":"Doctor@@2",
    "new_password":"Doctor@@1"
}


###
POST  http://127.0.0.1:8000/doctors/reset-password/d1554f79-d9c9-4774-a4af-b0a608e3c9f8/
Authorization: Token eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQzODc0NzIwLCJpYXQiOjE3NDM4NzExMjAsImp0aSI6IjU0YzY2OWZhM2RlNjQ0NGFhZDVkOTQwNTUwM2ZlYThlIiwidXNlcl9pZCI6IjBmOGI0NGZjLWU3Y2ItNDAwZi04ZDVkLTI1ZTIwYTUxYzI3ZCIsImlzX3N1cGVydXNlciI6ZmFsc2UsImlzX3N0YWZmIjpmYWxzZSwiaXNfYWN0aXZlIjp0cnVlLCJkb2N0b3JfaWQiOiIwZjhiNDRmYy1lN2NiLTQwMGYtOGQ1ZC0yNWUyMGE1MWMyN2QiLCJpc3MiOiJkb2N0b3Jfc2VydmljZSIsImF1ZCI6WyJwYXRpZW50X3NlcnZpY2UiLCJtZWRpY2FsX3JlY29yZHNfc2VydmljZSIsImFwcG9pbnRtZW50X3NlcnZpY2UiXX0.CSA8Rm-UT14c6TVjit5HRuMqg26g9CIZGMXfZ-qpQgIWolaeJxpaHyJIvEnqxNFq21PSQpJ0GWdpsTPSl-6xfGQVfCBY_lRWCmWrugJ8l5CBUEZj04IBuT33bNqrrZy-u820BRS9xnGbL5rUWhJmkapgKPPC_vVigem7eJ1gA18NDPOPz7IqhR9wlO-FNmI_JiExRGMASbIZRWtBX6WscVGF5AiyD4C1DDYGy7-dSSSddqYKosu7Hd3wd7_f7mOxvfm9RmgCHGI4ZHb7WHAKKkbS-HsYvYlV4UPl0AU3Xhi_-Zn5S-HW8AsOWiqrrowRplLrAgZH2Ee8myQflL2zig
Content-Type: application/json

{
    "new_password":"Default@@1"
}

###
GET http://127.0.0.1:8000/doctors/me/
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQzODc4OTM0LCJpYXQiOjE3NDM4NzUzMzQsImp0aSI6ImM1M2U5YzRkZjVjZTQxMjBhNzlhYzYzNjkxYzA1MzIxIiwiZG9jdG9yX2lkIjoiMGY4YjQ0ZmMtZTdjYi00MDBmLThkNWQtMjVlMjBhNTFjMjdkIiwiaXNfc3VwZXJ1c2VyIjpmYWxzZSwiaXNfc3RhZmYiOmZhbHNlLCJpc19hY3RpdmUiOnRydWUsInVzZXJfaWQiOiIwZjhiNDRmYy1lN2NiLTQwMGYtOGQ1ZC0yNWUyMGE1MWMyN2QiLCJpc3MiOiJkb2N0b3Jfc2VydmljZSIsImF1ZCI6WyJwYXRpZW50X3NlcnZpY2UiLCJtZWRpY2FsX3JlY29yZHNfc2VydmljZSIsImFwcG9pbnRtZW50X3NlcnZpY2UiXX0.eE_oXIJICRx5ITcgwNb3QJkHitycDG3g_EodoeFBy_7YvPY8v9EyS1_Kh_2KB0b_okA-9XadQHiYj22Fj_B_AppJEKimXzeV0xEgqc67UCdZRpS_ORE4s5hOpbtSqXCCZmL3GRPkiEIhMDlM10Kogq9tR-M3E9stW8scag0rIsmLXFc8gdVqwM5Sc3sr01Dn1ivE02IbOMrJUtsRqFtU-_I6Rd9XQ9FMOqATKdUHvBpFv31PMsHFrTQOhpNX4-t39spUavqtDnWmt1jauRJT7PcWvfWQb36EOL0kGUhAXV4uGFWxk6fNB8mvPAPbklir9jZ1pwWdWyagmdZF3xqCog