POST http://127.0.0.1:8001/appointments/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ1MzM1MjcwLCJpYXQiOjE3NDUzMzM0NzAsImp0aSI6ImRkZjg4Y2EyNzY0MzRlYzJhMGY2YzljYzNlYjEzNzI0IiwidXNlcl9pZCI6IjAzNzRiMjkxLWQ4NDUtNDkzNS1hMzdkLTg2ZGQ4ODU0MzIxOCIsImlzX3N1cGVydXNlciI6ZmFsc2UsImlzX3N0YWZmIjpmYWxzZSwiaXNfYWN0aXZlIjp0cnVlLCJpc3MiOiJwYXRpZW50X3NlcnZpY2UiLCJhdWQiOlsiYXBwb2ludG1lbnRfc2VydmljZSIsImRvY3Rvcl9zZXJ2aWNlIiwibWVkaWNhbF9yZWNvcmRzX3NlcnZpY2UiXSwicm9sZSI6InBhdGllbnQifQ.JeWvy07SJOCPsZPvvL85F7T8ggnx7Mj78-6dA2QBFYLUFgM9vMr7GuUv25IPI110xqwUvgQYhd1s8yP4uBvgGuu42bKw8aD770G4E_m2vpiyg4hQove_FvFeLulLxwqhWrHwOFzzYwF0TBfF0Plisr3nx5N0ZniAMVBC2HtTB7enBw0fJ_LyA2i_PKxGvZTDiWOPBjhWpHBxRmOAUvpUBTOecvq98d5VsRfD1iM5YME65SRrvViZEN6CGgUfZKzXnP5eyEKEp8pyz8j7K2Kd_O0z4RW5XGFrWL0i05dcV4YIXzk1lEh9fpjl-E_ZjCdi1jEWo4Km55J-O6Vaj1t7Lw

{
    "doctor_id":"4fa167ac-8304-4f2a-93c7-5b2fdc3207c7",
    "patient_id":"0374b291-d845-4935-a37d-86dd88543218",
    "date":"2025-6-23",
    "start_time":"15:10:00"
}

###

PUT http://127.0.0.1:8001/appointments/status/1d0a99e1-97a4-4e90-8841-b0aef802cd1c/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ0MDU1ODQ1LCJpYXQiOjE3NDQwNTIyNDUsImp0aSI6Ijk5YjRmNjRkNjY3ODRjMzVhYWU4OGE3NjlkOWRkYWNmIiwidXNlcl9pZCI6IjBmOGI0NGZjLWU3Y2ItNDAwZi04ZDVkLTI1ZTIwYTUxYzI3ZCIsImlzX3N1cGVydXNlciI6ZmFsc2UsImlzX3N0YWZmIjpmYWxzZSwiaXNfYWN0aXZlIjp0cnVlLCJpc3MiOiJkb2N0b3Jfc2VydmljZSIsImF1ZCI6WyJwYXRpZW50X3NlcnZpY2UiLCJtZWRpY2FsX3JlY29yZHNfc2VydmljZSIsImFwcG9pbnRtZW50X3NlcnZpY2UiXSwicm9sZSI6ImRvY3RvciJ9.hAuPIOlFDu4qkaITxpiL1gS3qmSbqXVpFb-VC0l_XsnT05jGg57sBXUaINOmACr153-xpYjqVHOZzdop10HrrHD6kNjLcGTMB6M2Z8zCh3R_EbY3M69b-DRtCMzGxP8nB5avZqOPFyVP_RyF2OoKrOvGRiRLvpTyUFn72UDEFRpKp8ejScHgbLoGLHpA3BDrjBe18hVINBVOTxExFIC-IaXZ2NB2M_cjdYW7dyfHaOGBdpYOIFGTN2eukAHhsIgaHsZ4XOEpI3GMUsQGGQdrzpBia95KcYxaNecCJWZ4WZiG037don-DGWm0BInLwsizKETmjJxyJRUDKlDmA4bIYQ

{
    "status":2
}

###
GET http://127.0.0.1:8001/appointments/
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ1MzI2MTI3LCJpYXQiOjE3NDUzMjQzMjcsImp0aSI6IjRhMzM1ZWIyMWRmNjQwZGM5NjEzZmEyNTI5MjlkMmRkIiwidXNlcl9pZCI6IjAzNzRiMjkxLWQ4NDUtNDkzNS1hMzdkLTg2ZGQ4ODU0MzIxOCIsImlzX3N1cGVydXNlciI6ZmFsc2UsImlzX3N0YWZmIjpmYWxzZSwiaXNfYWN0aXZlIjp0cnVlLCJpc3MiOiJwYXRpZW50X3NlcnZpY2UiLCJhdWQiOlsiYXBwb2ludG1lbnRfc2VydmljZSIsImRvY3Rvcl9zZXJ2aWNlIiwibWVkaWNhbF9yZWNvcmRzX3NlcnZpY2UiXSwicm9sZSI6InBhdGllbnQifQ.IaQBr8S4pmHpQ8vopUrWXJbVaa_TCtFUgEmZWiYEwwX3prrHc8-9aroDxFhEkn1pBXsnkB8SojBd8lG3r4ZXugbNBcyMXXdnFOIMbA9v6PyUQ7dTsrYOPAael4rI8jyGYg9kATbmgKdTvyvYkE_k1B1URNk-u4tk2Eb3tJ-2V1muEtfZHABgP1Zd_XPtTD1ElzwbEbf9G9xaCQs8BvGl0S6B9XkOMkr8FnW9LuRmc7YCXCvW8DH8KVHyjVYOBVvvAnA9AXtKN-gD0qqTMUfr9xTIAezNV9oPkc18aKhpZ8cyIeST5RX5sHB95SvsU4WX8VulbdzD01GspA-sxJRtVw

###
GET http://127.0.0.1:8001/appointments/patient/me/
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ1MzI3OTc2LCJpYXQiOjE3NDUzMjYxNzYsImp0aSI6ImJlOWVkMDI5ZGVjMjQ0NjBhOGUxZjU5OTQzZTk3MjY5IiwidXNlcl9pZCI6IjAzNzRiMjkxLWQ4NDUtNDkzNS1hMzdkLTg2ZGQ4ODU0MzIxOCIsImlzX3N1cGVydXNlciI6ZmFsc2UsImlzX3N0YWZmIjpmYWxzZSwiaXNfYWN0aXZlIjp0cnVlLCJpc3MiOiJwYXRpZW50X3NlcnZpY2UiLCJhdWQiOlsiYXBwb2ludG1lbnRfc2VydmljZSIsImRvY3Rvcl9zZXJ2aWNlIiwibWVkaWNhbF9yZWNvcmRzX3NlcnZpY2UiXSwicm9sZSI6InBhdGllbnQifQ.fJBLkPuQpZy9FDpSLguIbbucgd5OUv7PM1GbSV8LnRd2KDpSgivnDiWzx1SY3wIut6kk8Y-Np1Q4tLqg4Sse7DD_Sy9sr6v5T3YOdi2TQ6PizUzQoYfF9akq3XP9eR2Vhza5pjAs2NohUOiacK_ZqqTF8Yom0dk_mtiRwXzcqUZZGv5fzIBPUX7x4x8b748XFBYh-zZLyUB9zV_Woc2ujbiaD7QR2vtCFQCENKTY6OC3E0fDBIrImjyOAAd0pJcyxS3XCc4qtuE9eQsL11zZzQt78QQk6VEeiMCdbnDNzfYhsLbFxrQA5ZNGy-QDOr5vdJGERvmdHHpkxgREHujclA

###
GET http://127.0.0.1:8001/appointments/doctor/me/
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ1MzMzOTA2LCJpYXQiOjE3NDUzMzAzMDYsImp0aSI6ImJkYWE1NTMwOWU5YTRkMWQ4YzVlMzI2MzcyNmQxMjhlIiwidXNlcl9pZCI6IjRmYTE2N2FjLTgzMDQtNGYyYS05M2M3LTViMmZkYzMyMDdjNyIsImlzX3N1cGVydXNlciI6ZmFsc2UsImlzX3N0YWZmIjpmYWxzZSwiaXNfYWN0aXZlIjp0cnVlLCJpc3MiOiJkb2N0b3Jfc2VydmljZSIsImF1ZCI6WyJwYXRpZW50X3NlcnZpY2UiLCJtZWRpY2FsX3JlY29yZHNfc2VydmljZSIsImFwcG9pbnRtZW50X3NlcnZpY2UiXSwicm9sZSI6ImRvY3RvciJ9.jirp9PRX9AdzG3CVizrqSNXNvlf-CaGXegrdNmm25INNjsOg8Dicu_brQes3PevmvQeUyrPO23yQWHDknLOO8WuWX6UFpqt2JizV2RC3QYOffTl8dkgd8gfGNOxLC-hRrBwT6DZnQiXuHl7rvYIOroXONaLJ2o1sORZyufubnmAojDeks4PrVZl9yFx36Oeg0eBglbANjpAf4t2-7XhiNPpqn2Z5cRcToZPqIuJFial1axI3IMOt0iOwd38avzHB_r30RlhYU8bfrfLEuS-VJSXNwbaUwmybBgxGOYCm0i7o0IrsoPVIOtDPijW3al-p2vw641aIlNymmhL3CCckDA

###
GET http://127.0.0.1:8001/appointments/e0047ace-b705-46be-8114-31e039be982a/
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ1MzI3OTc2LCJpYXQiOjE3NDUzMjYxNzYsImp0aSI6ImJlOWVkMDI5ZGVjMjQ0NjBhOGUxZjU5OTQzZTk3MjY5IiwidXNlcl9pZCI6IjAzNzRiMjkxLWQ4NDUtNDkzNS1hMzdkLTg2ZGQ4ODU0MzIxOCIsImlzX3N1cGVydXNlciI6ZmFsc2UsImlzX3N0YWZmIjpmYWxzZSwiaXNfYWN0aXZlIjp0cnVlLCJpc3MiOiJwYXRpZW50X3NlcnZpY2UiLCJhdWQiOlsiYXBwb2ludG1lbnRfc2VydmljZSIsImRvY3Rvcl9zZXJ2aWNlIiwibWVkaWNhbF9yZWNvcmRzX3NlcnZpY2UiXSwicm9sZSI6InBhdGllbnQifQ.fJBLkPuQpZy9FDpSLguIbbucgd5OUv7PM1GbSV8LnRd2KDpSgivnDiWzx1SY3wIut6kk8Y-Np1Q4tLqg4Sse7DD_Sy9sr6v5T3YOdi2TQ6PizUzQoYfF9akq3XP9eR2Vhza5pjAs2NohUOiacK_ZqqTF8Yom0dk_mtiRwXzcqUZZGv5fzIBPUX7x4x8b748XFBYh-zZLyUB9zV_Woc2ujbiaD7QR2vtCFQCENKTY6OC3E0fDBIrImjyOAAd0pJcyxS3XCc4qtuE9eQsL11zZzQt78QQk6VEeiMCdbnDNzfYhsLbFxrQA5ZNGy-QDOr5vdJGERvmdHHpkxgREHujclA

###
PUT http://127.0.0.1:8001/appointments/b50a976c-c23a-41c6-a863-f270f4a8565d/reschedule/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ1MzMzOTA2LCJpYXQiOjE3NDUzMzAzMDYsImp0aSI6ImJkYWE1NTMwOWU5YTRkMWQ4YzVlMzI2MzcyNmQxMjhlIiwidXNlcl9pZCI6IjRmYTE2N2FjLTgzMDQtNGYyYS05M2M3LTViMmZkYzMyMDdjNyIsImlzX3N1cGVydXNlciI6ZmFsc2UsImlzX3N0YWZmIjpmYWxzZSwiaXNfYWN0aXZlIjp0cnVlLCJpc3MiOiJkb2N0b3Jfc2VydmljZSIsImF1ZCI6WyJwYXRpZW50X3NlcnZpY2UiLCJtZWRpY2FsX3JlY29yZHNfc2VydmljZSIsImFwcG9pbnRtZW50X3NlcnZpY2UiXSwicm9sZSI6ImRvY3RvciJ9.jirp9PRX9AdzG3CVizrqSNXNvlf-CaGXegrdNmm25INNjsOg8Dicu_brQes3PevmvQeUyrPO23yQWHDknLOO8WuWX6UFpqt2JizV2RC3QYOffTl8dkgd8gfGNOxLC-hRrBwT6DZnQiXuHl7rvYIOroXONaLJ2o1sORZyufubnmAojDeks4PrVZl9yFx36Oeg0eBglbANjpAf4t2-7XhiNPpqn2Z5cRcToZPqIuJFial1axI3IMOt0iOwd38avzHB_r30RlhYU8bfrfLEuS-VJSXNwbaUwmybBgxGOYCm0i7o0IrsoPVIOtDPijW3al-p2vw641aIlNymmhL3CCckDA

{
    "date":"2025-6-21",
    "start_time":"16:00:00"
}


###
POST http://127.0.0.1:8001/appointments/doctor/leave-period/
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ1MzM3NjQ0LCJpYXQiOjE3NDUzMzQwNDQsImp0aSI6ImI3Y2E2MzQzZGJkNjRiNDc4MGJkZTI5NmI5OThkOTZmIiwidXNlcl9pZCI6IjRmYTE2N2FjLTgzMDQtNGYyYS05M2M3LTViMmZkYzMyMDdjNyIsImlzX3N1cGVydXNlciI6ZmFsc2UsImlzX3N0YWZmIjpmYWxzZSwiaXNfYWN0aXZlIjp0cnVlLCJpc3MiOiJkb2N0b3Jfc2VydmljZSIsImF1ZCI6WyJwYXRpZW50X3NlcnZpY2UiLCJtZWRpY2FsX3JlY29yZHNfc2VydmljZSIsImFwcG9pbnRtZW50X3NlcnZpY2UiXSwicm9sZSI6ImRvY3RvciJ9.XvDaars9R4G9vRImfV8zQIPPOdSM-_8cUNUtz11VdsIhRSgm4YJAPXOfx9yV_5bV34Yk_MmtQLFmZ1hTLML1D1BTAuyUYDEQyyebzJ5rVFHRV6YAad3IOeD-BLALIukULuaMBs3o9qIacHDVgKrIOm0e9gnyfzyUSpTWFWwAB_ac7_d4KLoM9oV4-JCBjiKIMtXbTpEYpr4VD4yiARzi_CI-it8CImyt6HviRlDnb9_mXWhCBz79xbR0E2qoY2VsgNIpEnH8jhbE0-zL0qtkC0Gtd3PDgx6JmTZVdhgeVwMtrfYLtZy92J49-KPpLAqzEfBRrsI0SttmIlEe92_0Xw
Content-Type: application/json

{
    "start_date":"2025-6-24"
}

###
GET http://127.0.0.1:8001/appointments/doctor/leave-period/me/
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ1MzM3NjQ0LCJpYXQiOjE3NDUzMzQwNDQsImp0aSI6ImI3Y2E2MzQzZGJkNjRiNDc4MGJkZTI5NmI5OThkOTZmIiwidXNlcl9pZCI6IjRmYTE2N2FjLTgzMDQtNGYyYS05M2M3LTViMmZkYzMyMDdjNyIsImlzX3N1cGVydXNlciI6ZmFsc2UsImlzX3N0YWZmIjpmYWxzZSwiaXNfYWN0aXZlIjp0cnVlLCJpc3MiOiJkb2N0b3Jfc2VydmljZSIsImF1ZCI6WyJwYXRpZW50X3NlcnZpY2UiLCJtZWRpY2FsX3JlY29yZHNfc2VydmljZSIsImFwcG9pbnRtZW50X3NlcnZpY2UiXSwicm9sZSI6ImRvY3RvciJ9.XvDaars9R4G9vRImfV8zQIPPOdSM-_8cUNUtz11VdsIhRSgm4YJAPXOfx9yV_5bV34Yk_MmtQLFmZ1hTLML1D1BTAuyUYDEQyyebzJ5rVFHRV6YAad3IOeD-BLALIukULuaMBs3o9qIacHDVgKrIOm0e9gnyfzyUSpTWFWwAB_ac7_d4KLoM9oV4-JCBjiKIMtXbTpEYpr4VD4yiARzi_CI-it8CImyt6HviRlDnb9_mXWhCBz79xbR0E2qoY2VsgNIpEnH8jhbE0-zL0qtkC0Gtd3PDgx6JmTZVdhgeVwMtrfYLtZy92J49-KPpLAqzEfBRrsI0SttmIlEe92_0Xw