POST http://127.0.0.1:8001/appointments/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ0MDIzOTQwLCJpYXQiOjE3NDQwMjAzNDAsImp0aSI6ImIyNDM1MDM1MzBiMTRkNDVhMmUyYWRhNTYyMGNkNjJiIiwidXNlcl9pZCI6IjBmOGI0NGZjLWU3Y2ItNDAwZi04ZDVkLTI1ZTIwYTUxYzI3ZCIsImlzX3N1cGVydXNlciI6ZmFsc2UsImlzX3N0YWZmIjpmYWxzZSwiaXNfYWN0aXZlIjp0cnVlLCJpc3MiOiJkb2N0b3Jfc2VydmljZSIsImF1ZCI6WyJwYXRpZW50X3NlcnZpY2UiLCJtZWRpY2FsX3JlY29yZHNfc2VydmljZSIsImFwcG9pbnRtZW50X3NlcnZpY2UiXSwicm9sZSI6ImRvY3RvciJ9.IQMzWZ9woWfgOIe0uRUFV2hFRcIeVPA9nPysqr97EI8XAaFw5-zvjrn6LjDsfHfr18irHHR386MNvtVwytxdxLEd_j6XZmHfsoddn-mB2d0YDvuySjxAwVMHQOfmkfjhb9voeH14i_Ke0Swh5tlLUk097Z6AHG4QSw41enbDbQaZFNzOPIGdZaOn9zziIJvQZU_7KR3RKaomsJdfTe5xH2wXiMlzXNK9yOzhMVjYpLBdlPqOp0buCtUtpOyrYLroUkvr-KgWqZqQ08s9jiQPp7AJQ4QyivKbeDAkVoXxn6vPxNTcz4l8NQPw7bUyUBmnyuF2Om80yyzeQjM6-e_bDA

{
    "doctor_id":"0f8b44fc-e7cb-400f-8d5d-25e20a51c27d",
    "patient_id":"0a20cc04-3330-410c-9e1c-8737328d5140",
    "date":"2025-04-07",
    "start_time":"10:00:00"
}

###

PUT http://127.0.0.1:8001/appointments/status/cb619b13-cf88-4a2a-a184-0d7d7174901b/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ0MDIzOTQwLCJpYXQiOjE3NDQwMjAzNDAsImp0aSI6ImIyNDM1MDM1MzBiMTRkNDVhMmUyYWRhNTYyMGNkNjJiIiwidXNlcl9pZCI6IjBmOGI0NGZjLWU3Y2ItNDAwZi04ZDVkLTI1ZTIwYTUxYzI3ZCIsImlzX3N1cGVydXNlciI6ZmFsc2UsImlzX3N0YWZmIjpmYWxzZSwiaXNfYWN0aXZlIjp0cnVlLCJpc3MiOiJkb2N0b3Jfc2VydmljZSIsImF1ZCI6WyJwYXRpZW50X3NlcnZpY2UiLCJtZWRpY2FsX3JlY29yZHNfc2VydmljZSIsImFwcG9pbnRtZW50X3NlcnZpY2UiXSwicm9sZSI6ImRvY3RvciJ9.IQMzWZ9woWfgOIe0uRUFV2hFRcIeVPA9nPysqr97EI8XAaFw5-zvjrn6LjDsfHfr18irHHR386MNvtVwytxdxLEd_j6XZmHfsoddn-mB2d0YDvuySjxAwVMHQOfmkfjhb9voeH14i_Ke0Swh5tlLUk097Z6AHG4QSw41enbDbQaZFNzOPIGdZaOn9zziIJvQZU_7KR3RKaomsJdfTe5xH2wXiMlzXNK9yOzhMVjYpLBdlPqOp0buCtUtpOyrYLroUkvr-KgWqZqQ08s9jiQPp7AJQ4QyivKbeDAkVoXxn6vPxNTcz4l8NQPw7bUyUBmnyuF2Om80yyzeQjM6-e_bDA

{
    "status":1
}

###
GET http://127.0.0.1:8001/appointments/
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ0MDMxNTkyLCJpYXQiOjE3NDQwMjc5OTIsImp0aSI6ImRkZjFhZDA5NTkzODRhYzliZDNhNWY4YmRhNDE5YTc1IiwidXNlcl9pZCI6IjBmOGI0NGZjLWU3Y2ItNDAwZi04ZDVkLTI1ZTIwYTUxYzI3ZCIsImlzX3N1cGVydXNlciI6ZmFsc2UsImlzX3N0YWZmIjpmYWxzZSwiaXNfYWN0aXZlIjp0cnVlLCJpc3MiOiJkb2N0b3Jfc2VydmljZSIsImF1ZCI6WyJwYXRpZW50X3NlcnZpY2UiLCJtZWRpY2FsX3JlY29yZHNfc2VydmljZSIsImFwcG9pbnRtZW50X3NlcnZpY2UiXSwicm9sZSI6ImRvY3RvciJ9.D3jeW6uFM6EkN0LX76U2wmgeA6e7ghjDvn_dn_c4csiZ89XDqzQN9ofmwJVKLZU8PJuU_GwmD6Coj85qzZ9C05eNBZnsoFzpe_70E_hxxYnxxeFShbvyll9ko2H3Q6UvlKzdrtjr9guRUpapRpXdj-8CryI8B9Z6y2-YCjCFq6C6RSS4LMhK4R8xkna4-hWr5BcCz2KWzyiQnGbrRVAN1xNn1P-u8_ms9IqkvdIB1BIPGAmzIGz4nRd9yXNJfieyekb0TY6pmpMr9EjjYxJL6tDiPnWe0bEbTME1JYlT-L7jrjDx9hIPi2sD_ZPfg57UpI6-vgVz9M_3ya-MIpvohA

###
GET http://127.0.0.1:8001/appointments/patient/
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ0MDMxNTkyLCJpYXQiOjE3NDQwMjc5OTIsImp0aSI6ImRkZjFhZDA5NTkzODRhYzliZDNhNWY4YmRhNDE5YTc1IiwidXNlcl9pZCI6IjBmOGI0NGZjLWU3Y2ItNDAwZi04ZDVkLTI1ZTIwYTUxYzI3ZCIsImlzX3N1cGVydXNlciI6ZmFsc2UsImlzX3N0YWZmIjpmYWxzZSwiaXNfYWN0aXZlIjp0cnVlLCJpc3MiOiJkb2N0b3Jfc2VydmljZSIsImF1ZCI6WyJwYXRpZW50X3NlcnZpY2UiLCJtZWRpY2FsX3JlY29yZHNfc2VydmljZSIsImFwcG9pbnRtZW50X3NlcnZpY2UiXSwicm9sZSI6ImRvY3RvciJ9.D3jeW6uFM6EkN0LX76U2wmgeA6e7ghjDvn_dn_c4csiZ89XDqzQN9ofmwJVKLZU8PJuU_GwmD6Coj85qzZ9C05eNBZnsoFzpe_70E_hxxYnxxeFShbvyll9ko2H3Q6UvlKzdrtjr9guRUpapRpXdj-8CryI8B9Z6y2-YCjCFq6C6RSS4LMhK4R8xkna4-hWr5BcCz2KWzyiQnGbrRVAN1xNn1P-u8_ms9IqkvdIB1BIPGAmzIGz4nRd9yXNJfieyekb0TY6pmpMr9EjjYxJL6tDiPnWe0bEbTME1JYlT-L7jrjDx9hIPi2sD_ZPfg57UpI6-vgVz9M_3ya-MIpvohA