POST http://127.0.0.1:8000/patients/register/
Content-Type: application/json

{
    "first_name":"John",
    "last_name":"Doe",
    "surname":"Smith",
    "email":"johndoke@gmail.com",
    "password":"Patient@@1",
    "phone":"254700000700",
    "id_number":"12345677",
    "residence": "Thika, Kiambu",
    "occupation": "Unknown",
    "gender":0
}


###
POST http://127.0.0.1:8006/patients/login/
Content-Type: application/json

{
    "email":"lenaealf@gmail.com",
    "password": "Patient@@1"
}

###
POST http://127.0.0.1:8006/patients/me/dependents/register/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ4MTg5MDI2LCJpYXQiOjE3NDgxODcyMjYsImp0aSI6ImUzMTY4NTBjYjQ0MjQ3YmE5ZmNiOWUwOTU2YjA4MmI5IiwidXNlcl9pZCI6IjBmMTliNWMyLTA2MzMtNGQzNi1hNDU4LTNkMGQ5ZmM4OTI5ZCIsImlzX3N1cGVydXNlciI6ZmFsc2UsImlzX3N0YWZmIjpmYWxzZSwiaXNfYWN0aXZlIjp0cnVlLCJpc3MiOiJwYXRpZW50X3NlcnZpY2UiLCJhdWQiOlsiYXBwb2ludG1lbnRfc2VydmljZSIsImRvY3Rvcl9zZXJ2aWNlIiwibWVkaWNhbF9yZWNvcmRzX3NlcnZpY2UiXSwicm9sZSI6InBhdGllbnQifQ.JfwKCz02xvwHyo3KtJycgZYFvNA7GRoC6_krKZ_8uoE1arAGG4qgnNXXXJdxACGW6GwiRDF6ZaXgPcyPG0WbaPhlUx7SfsLkJgU-9tXl5ZkIBvr80PZm79v_vFy5rJyrWYV9ITpHbxpp-Iujcq94DBu0zYFVlPtuovqBoaJwMu9TL1VyUnVymyQG3JHF0Ac_isdB63mlU53wGBAYRejPC83R9nP08JyoqsszURhKl0tgU0d1hVRV_zNXRvnL_jGaEefYZDBqZ8Tl5BDHWtlNEWmltEaVQGV0IVFToL-uu5AuTh6jOYDHtOYeVOurgH67GzRNgAIdum0fqy1EJvCh6w

{
    "dependent":{
        "first_name":"Lazarus",
        "last_name":"Maina",
        "surname":"Raztaf",
        "date_of_birth":"2010-02-11",
        "gender":0
    },
    "relationship":"father"
}
###
GET http://127.0.0.1:8006/patients/me/dependents/
Authorization: Bearer  eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ4MTg5MDI2LCJpYXQiOjE3NDgxODcyMjYsImp0aSI6ImUzMTY4NTBjYjQ0MjQ3YmE5ZmNiOWUwOTU2YjA4MmI5IiwidXNlcl9pZCI6IjBmMTliNWMyLTA2MzMtNGQzNi1hNDU4LTNkMGQ5ZmM4OTI5ZCIsImlzX3N1cGVydXNlciI6ZmFsc2UsImlzX3N0YWZmIjpmYWxzZSwiaXNfYWN0aXZlIjp0cnVlLCJpc3MiOiJwYXRpZW50X3NlcnZpY2UiLCJhdWQiOlsiYXBwb2ludG1lbnRfc2VydmljZSIsImRvY3Rvcl9zZXJ2aWNlIiwibWVkaWNhbF9yZWNvcmRzX3NlcnZpY2UiXSwicm9sZSI6InBhdGllbnQifQ.JfwKCz02xvwHyo3KtJycgZYFvNA7GRoC6_krKZ_8uoE1arAGG4qgnNXXXJdxACGW6GwiRDF6ZaXgPcyPG0WbaPhlUx7SfsLkJgU-9tXl5ZkIBvr80PZm79v_vFy5rJyrWYV9ITpHbxpp-Iujcq94DBu0zYFVlPtuovqBoaJwMu9TL1VyUnVymyQG3JHF0Ac_isdB63mlU53wGBAYRejPC83R9nP08JyoqsszURhKl0tgU0d1hVRV_zNXRvnL_jGaEefYZDBqZ8Tl5BDHWtlNEWmltEaVQGV0IVFToL-uu5AuTh6jOYDHtOYeVOurgH67GzRNgAIdum0fqy1EJvCh6w

###
DELETE http://127.0.0.1:8006/patients/me/dependents/detail/38fe07db-80aa-4055-85a2-81562d0ed523/
Content-Type: application/json
Authorization: Bearer  eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ4MTg5MDI2LCJpYXQiOjE3NDgxODcyMjYsImp0aSI6ImUzMTY4NTBjYjQ0MjQ3YmE5ZmNiOWUwOTU2YjA4MmI5IiwidXNlcl9pZCI6IjBmMTliNWMyLTA2MzMtNGQzNi1hNDU4LTNkMGQ5ZmM4OTI5ZCIsImlzX3N1cGVydXNlciI6ZmFsc2UsImlzX3N0YWZmIjpmYWxzZSwiaXNfYWN0aXZlIjp0cnVlLCJpc3MiOiJwYXRpZW50X3NlcnZpY2UiLCJhdWQiOlsiYXBwb2ludG1lbnRfc2VydmljZSIsImRvY3Rvcl9zZXJ2aWNlIiwibWVkaWNhbF9yZWNvcmRzX3NlcnZpY2UiXSwicm9sZSI6InBhdGllbnQifQ.JfwKCz02xvwHyo3KtJycgZYFvNA7GRoC6_krKZ_8uoE1arAGG4qgnNXXXJdxACGW6GwiRDF6ZaXgPcyPG0WbaPhlUx7SfsLkJgU-9tXl5ZkIBvr80PZm79v_vFy5rJyrWYV9ITpHbxpp-Iujcq94DBu0zYFVlPtuovqBoaJwMu9TL1VyUnVymyQG3JHF0Ac_isdB63mlU53wGBAYRejPC83R9nP08JyoqsszURhKl0tgU0d1hVRV_zNXRvnL_jGaEefYZDBqZ8Tl5BDHWtlNEWmltEaVQGV0IVFToL-uu5AuTh6jOYDHtOYeVOurgH67GzRNgAIdum0fqy1EJvCh6w

{
    "relationship":"father",
    "dependent": {
      "first_name": "Janet",
      "last_name": "Ambanyo",
      "surname": "Raztaf",
      "email": "janetambayo@gmail.com",
      "phone": "25412166018"
    }
}

###
POST http://localhost:8000/patients/login/
Content-Type: application/json

{
    "email":"johndoe@gmail.com",
    "password": "Patient@@1"
}

###
GET http://127.0.0.1:8000/patients/
Content-Type: application/json
Authorization: Bearer Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ3Mzk4ODIwLCJpYXQiOjE3NDczOTcwMjAsImp0aSI6ImExZTE2YjM1ODdiMTQ4MGM4MTcxYjNmNjFlNzAzNjhkIiwidXNlcl9pZCI6IjAzNzRiMjkxLWQ4NDUtNDkzNS1hMzdkLTg2ZGQ4ODU0MzIxOCIsImlzX3N1cGVydXNlciI6ZmFsc2UsImlzX3N0YWZmIjpmYWxzZSwiaXNfYWN0aXZlIjp0cnVlLCJpc3MiOiJwYXRpZW50X3NlcnZpY2UiLCJhdWQiOlsiYXBwb2ludG1lbnRfc2VydmljZSIsImRvY3Rvcl9zZXJ2aWNlIiwibWVkaWNhbF9yZWNvcmRzX3NlcnZpY2UiXSwicm9sZSI6InBhdGllbnQifQ.JY_8XfopN8p1OCqGzh_Se5wA6cQUqH5Rd1QsYYj_J-ajBiok38h2xOAyQUfmYUVmDznMavS_qdCAKknl8RrGJbgjt98gj1I33xWePM8b9T9WyQZQQ01rEdk9lXpRdu2TvjG1Hh-XiimudY8ku9QxVOzq2EDY6D4HMMjUig_jMumsuZZsXD1ulqqBDaRLiX08XmQUDb80jYxMreEx1O29uG-pBluKcv3dLgyTjLArJM6eEDfHlgffAr0W7UWJ2SG4sX5y2aEk0MR97M7eHiIfnPnREOVXJ7bbFDHOfUb-UcFdZcyFayCVeuM9RcEmdMI2nJ08Cl5H1P85L8-pjy2U5A

###
PUT  http://127.0.0.1:8006/patients/self/update/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ3NDEzOTg4LCJpYXQiOjE3NDc0MTIxODgsImp0aSI6ImE5NmI2OGFiMDU4NTRmOTE5NjU2NjhiZmJlYjUyMDIwIiwidXNlcl9pZCI6IjAzNzRiMjkxLWQ4NDUtNDkzNS1hMzdkLTg2ZGQ4ODU0MzIxOCIsImlzX3N1cGVydXNlciI6ZmFsc2UsImlzX3N0YWZmIjpmYWxzZSwiaXNfYWN0aXZlIjp0cnVlLCJpc3MiOiJwYXRpZW50X3NlcnZpY2UiLCJhdWQiOlsiYXBwb2ludG1lbnRfc2VydmljZSIsImRvY3Rvcl9zZXJ2aWNlIiwibWVkaWNhbF9yZWNvcmRzX3NlcnZpY2UiXSwicm9sZSI6InBhdGllbnQifQ.QbC3iw5Qs9UeL7NTtT8GG2ayf9x4qsS4Hxpg-J-faNWKFXGPuFnF3pA78wZ3pgMDaAAZbtyaYEDrJWIxL6_l25cplbqpmnZqGCe8DQVuGXvgaig4pZJ5WV8yehj9wayBE7CCtBJLiqPkBWa_pIV5UVfE9_LYSCISUebDdVooOHKq-5bdE3fsLdzO8tkMpnFum0aT1aFxugvkyZlPvUj-JOWM2Zc_QuG-lx2_gBZzla1WtpMUp3HCtuTHVGjtatPhnUUNJWxNCQ0T8kVAla05LZmdscJU9aHix4yae-1CnDh7aw7-ptZVFtz1KRZJyjUNMUTnnjL6KftXKk7iSkSWMg

{
    "first_name":"Jonathan",
    "last_name":"Doe",
    "surname":"Smith",
    "email":"lenaealf@gmail.com",
    "password":"Patient@@1",
    "phone":"254700000002",
    "id_number":"12345678",
    "residence": "Kirigiti, Kiambu",
    "occupation": "plumber",
    "gender":0,
    "next_of_kin": {
        "first_name":"Daughter",
        "last_name":"next of kin",
        "email":"nok@email.com",
        "phone":"254711111111",
        "relationship":"daughter"
    }
}

###
DELETE http://127.0.0.1:8000/patients/c6b4b160-e968-4698-bb24-ea5e5099adc5/
Content-Type: application/json
Authorization: Token eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ0OTk3MDEyLCJpYXQiOjE3NDQ5OTUyMTIsImp0aSI6IjgzN2I1YjVjMzdmZTRlMTBhOWM2ZTAxZTlhMWM3ZmE5IiwidXNlcl9pZCI6ImM2YjRiMTYwLWU5NjgtNDY5OC1iYjI0LWVhNWU1MDk5YWRjNSIsImlzX3N1cGVydXNlciI6ZmFsc2UsImlzX3N0YWZmIjpmYWxzZSwiaXNfYWN0aXZlIjp0cnVlLCJpc3MiOiJwYXRpZW50X3NlcnZpY2UiLCJhdWQiOlsiYXBwb2ludG1lbnRfc2VydmljZSIsImRvY3Rvcl9zZXJ2aWNlIiwibWVkaWNhbF9yZWNvcmRzX3NlcnZpY2UiXSwicm9sZSI6InBhdGllbnQifQ.bLXmjOuqUdS7J8rHWXbTewFyDaTeQ2SrbSLLsyctClfivXyGY1LDWBO7QKZINZCoPcnG0UXWtdMt3qgbuS28PxnHetYG6_eSdYJNTMoFATgErd7iTXji_TpHlDb2WbjylcE1DIVAbPbetHUB4LttxyshfhpXHAvv7Y_5-Mtbpvwt-4YfODPxcdtTzmPPLLvOoak__ZhtrUqmWl7Azhgn3BkndXvvlzhTRa3isr9cVglZ8d5U3IeH4fK-kdq1X5ojmR0CRDhazhAnWtXh5qfT2jIebrFFnC5JTMeJ9zuY3x2QBdRvKdcaLMnQd6niV1M_5Pjl8jdzGxTxBkJHZ0ZOHQ

###
GET  http://127.0.0.1:8000/patients/abde4fab-f1e8-42ab-8460-2fa761a4ea03/
Content-Type: application/json
Authorization: Token eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ0OTk1OTUwLCJpYXQiOjE3NDQ5OTQxNTAsImp0aSI6IjFlYTAwM2YxODMwNjQzZjViNjVjZTUxZTAwNjNhNTFlIiwidXNlcl9pZCI6ImFiZGU0ZmFiLWYxZTgtNDJhYi04NDYwLTJmYTc2MWE0ZWEwMyIsImlzX3N1cGVydXNlciI6ZmFsc2UsImlzX3N0YWZmIjpmYWxzZSwiaXNfYWN0aXZlIjp0cnVlLCJpc3MiOiJwYXRpZW50X3NlcnZpY2UiLCJhdWQiOlsiYXBwb2ludG1lbnRfc2VydmljZSIsImRvY3Rvcl9zZXJ2aWNlIiwibWVkaWNhbF9yZWNvcmRzX3NlcnZpY2UiXSwicm9sZSI6InBhdGllbnQifQ.b7pF_GsQof2LUctT0NX1dqbjN_WQzmhDfoXYJDdSI3T6wq5NaZa6mwPPMkWnLZ7Fkrpc09NB7hkQM_0_cDejwqLBnv1QqryGhi4E0vpStx_x9cAXWU411fdNsPHNCxk1FiXSM9DgPW4FQn8S-TOhaUoE9HFxkbkqKMKHTM9ND-uJlyL6pVLJoN0jg7pDBzr57uuK8fIZafclg0gPmcBWXLvaMWaeEaWRdO2kqsUIAwIKS5moos-99tXkDyc1CmQZsY4gGtBPBosPQ3GANVt9yyz26EKF4xt9pDWJk0qPz7GR-i3jX0dRMIaxnfiBpo7ttqyaafF0UyvUjJEmSO0oyg

###
GET http://127.0.0.1:8000/patients/me/
Content-Type: application/json
Authorization: Token eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ0OTk1OTUwLCJpYXQiOjE3NDQ5OTQxNTAsImp0aSI6IjFlYTAwM2YxODMwNjQzZjViNjVjZTUxZTAwNjNhNTFlIiwidXNlcl9pZCI6ImFiZGU0ZmFiLWYxZTgtNDJhYi04NDYwLTJmYTc2MWE0ZWEwMyIsImlzX3N1cGVydXNlciI6ZmFsc2UsImlzX3N0YWZmIjpmYWxzZSwiaXNfYWN0aXZlIjp0cnVlLCJpc3MiOiJwYXRpZW50X3NlcnZpY2UiLCJhdWQiOlsiYXBwb2ludG1lbnRfc2VydmljZSIsImRvY3Rvcl9zZXJ2aWNlIiwibWVkaWNhbF9yZWNvcmRzX3NlcnZpY2UiXSwicm9sZSI6InBhdGllbnQifQ.b7pF_GsQof2LUctT0NX1dqbjN_WQzmhDfoXYJDdSI3T6wq5NaZa6mwPPMkWnLZ7Fkrpc09NB7hkQM_0_cDejwqLBnv1QqryGhi4E0vpStx_x9cAXWU411fdNsPHNCxk1FiXSM9DgPW4FQn8S-TOhaUoE9HFxkbkqKMKHTM9ND-uJlyL6pVLJoN0jg7pDBzr57uuK8fIZafclg0gPmcBWXLvaMWaeEaWRdO2kqsUIAwIKS5moos-99tXkDyc1CmQZsY4gGtBPBosPQ3GANVt9yyz26EKF4xt9pDWJk0qPz7GR-i3jX0dRMIaxnfiBpo7ttqyaafF0UyvUjJEmSO0oyg

###
PUT http://127.0.0.1:8000/patients/me/password/
Content-Type: application/json
Authorization: Token eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQzNzg2ODI0LCJpYXQiOjE3NDM3ODUwMjQsImp0aSI6ImE3YzFiM2ZjMTRkMTRhZjNiODNiM2I2NTk5YWUzYTk1IiwidXNlcl9pZCI6IjBhMjBjYzA0LTMzMzAtNDEwYy05ZTFjLTg3MzczMjhkNTE0MCIsImlzX3N1cGVydXNlciI6ZmFsc2UsImlzX3N0YWZmIjpmYWxzZSwiaXNfYWN0aXZlIjp0cnVlLCJwYXRpZW50X2lkIjoiMGEyMGNjMDQtMzMzMC00MTBjLTllMWMtODczNzMyOGQ1MTQwIiwiaXNzIjoidXNlcl9zZXJ2aWNlIiwiYXVkIjpbImFwcG9pbnRtZW50X3NlcnZpY2UiLCJkb2N0b3Jfc2VydmljZSIsIm1lZGljYWxfcmVjb3Jkc19zZXJ2aWNlIl19.A9afo01sTFGKaAp96v19PlC5-eBx1q_VBt3us-f55wR2kssLH0K-iS-hRUKDBGPk6LwvYP3FACFUODRz19o2d1DNTJXdko6t8Fl2KGu5f4PCN0_TWwMrCCUVrhaIXdLiIwB_a-sG_pe11MuK9JFpzJ85WKuJ6SmTx_ugOhXVvkK-pyxa9Htdf07lQsykg6oMWXhnhNw08X8V8lkvuTpe9wnXWq3FPWUHp4ZRDxq6X3xr1dwQi8F1O9AgsPwqRCEDd8lsdBTK7_XSrNqt6YPtDbI9zTuw_K4l0yo-gsIDZpr9gcz9VrL4hPki7C3nPRwH40l5n9GSx4dvo9nj62pVOA

{
    "old_password":"Admin@@1",
    "new_password":"Patient@@1"
}

###
GET http://127.0.0.1:8000/patients/status/0a20cc04-3330-410c-9e1c-8737328d5140/
Content-Type: application/json
Authorization: Token eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQzNzg2ODI0LCJpYXQiOjE3NDM3ODUwMjQsImp0aSI6ImE3YzFiM2ZjMTRkMTRhZjNiODNiM2I2NTk5YWUzYTk1IiwidXNlcl9pZCI6IjBhMjBjYzA0LTMzMzAtNDEwYy05ZTFjLTg3MzczMjhkNTE0MCIsImlzX3N1cGVydXNlciI6ZmFsc2UsImlzX3N0YWZmIjpmYWxzZSwiaXNfYWN0aXZlIjp0cnVlLCJwYXRpZW50X2lkIjoiMGEyMGNjMDQtMzMzMC00MTBjLTllMWMtODczNzMyOGQ1MTQwIiwiaXNzIjoidXNlcl9zZXJ2aWNlIiwiYXVkIjpbImFwcG9pbnRtZW50X3NlcnZpY2UiLCJkb2N0b3Jfc2VydmljZSIsIm1lZGljYWxfcmVjb3Jkc19zZXJ2aWNlIl19.A9afo01sTFGKaAp96v19PlC5-eBx1q_VBt3us-f55wR2kssLH0K-iS-hRUKDBGPk6LwvYP3FACFUODRz19o2d1DNTJXdko6t8Fl2KGu5f4PCN0_TWwMrCCUVrhaIXdLiIwB_a-sG_pe11MuK9JFpzJ85WKuJ6SmTx_ugOhXVvkK-pyxa9Htdf07lQsykg6oMWXhnhNw08X8V8lkvuTpe9wnXWq3FPWUHp4ZRDxq6X3xr1dwQi8F1O9AgsPwqRCEDd8lsdBTK7_XSrNqt6YPtDbI9zTuw_K4l0yo-gsIDZpr9gcz9VrL4hPki7C3nPRwH40l5n9GSx4dvo9nj62pVOA

{
    "is_active": true
}