POST http://127.0.0.1:8000/patients/register/
Content-Type: application/json

{
    "first_name":"Test",
    "last_name":"Patient",
    "surname":"Delete",
    "email":"ftpd@gmail.com",
    "password":"Patient@@1",
    "phone":"254700000001",
    "id_number":"12345679"
}

###
POST http://127.0.0.1:8000/patients/login/
Content-Type: application/json

{
    "email":"ftpd@gmail.com",
    "password": "Patient@@1"
}

###
GET http://127.0.0.1:8000/patients/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQzNzg2ODI0LCJpYXQiOjE3NDM3ODUwMjQsImp0aSI6ImE3YzFiM2ZjMTRkMTRhZjNiODNiM2I2NTk5YWUzYTk1IiwidXNlcl9pZCI6IjBhMjBjYzA0LTMzMzAtNDEwYy05ZTFjLTg3MzczMjhkNTE0MCIsImlzX3N1cGVydXNlciI6ZmFsc2UsImlzX3N0YWZmIjpmYWxzZSwiaXNfYWN0aXZlIjp0cnVlLCJwYXRpZW50X2lkIjoiMGEyMGNjMDQtMzMzMC00MTBjLTllMWMtODczNzMyOGQ1MTQwIiwiaXNzIjoidXNlcl9zZXJ2aWNlIiwiYXVkIjpbImFwcG9pbnRtZW50X3NlcnZpY2UiLCJkb2N0b3Jfc2VydmljZSIsIm1lZGljYWxfcmVjb3Jkc19zZXJ2aWNlIl19.A9afo01sTFGKaAp96v19PlC5-eBx1q_VBt3us-f55wR2kssLH0K-iS-hRUKDBGPk6LwvYP3FACFUODRz19o2d1DNTJXdko6t8Fl2KGu5f4PCN0_TWwMrCCUVrhaIXdLiIwB_a-sG_pe11MuK9JFpzJ85WKuJ6SmTx_ugOhXVvkK-pyxa9Htdf07lQsykg6oMWXhnhNw08X8V8lkvuTpe9wnXWq3FPWUHp4ZRDxq6X3xr1dwQi8F1O9AgsPwqRCEDd8lsdBTK7_XSrNqt6YPtDbI9zTuw_K4l0yo-gsIDZpr9gcz9VrL4hPki7C3nPRwH40l5n9GSx4dvo9nj62pVOA

###
PUT  http://127.0.0.1:8000/patients/0a20cc04-3330-410c-9e1c-8737328d5140/
Content-Type: application/json
Authorization: Token eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQzNzg2ODI0LCJpYXQiOjE3NDM3ODUwMjQsImp0aSI6ImE3YzFiM2ZjMTRkMTRhZjNiODNiM2I2NTk5YWUzYTk1IiwidXNlcl9pZCI6IjBhMjBjYzA0LTMzMzAtNDEwYy05ZTFjLTg3MzczMjhkNTE0MCIsImlzX3N1cGVydXNlciI6ZmFsc2UsImlzX3N0YWZmIjpmYWxzZSwiaXNfYWN0aXZlIjp0cnVlLCJwYXRpZW50X2lkIjoiMGEyMGNjMDQtMzMzMC00MTBjLTllMWMtODczNzMyOGQ1MTQwIiwiaXNzIjoidXNlcl9zZXJ2aWNlIiwiYXVkIjpbImFwcG9pbnRtZW50X3NlcnZpY2UiLCJkb2N0b3Jfc2VydmljZSIsIm1lZGljYWxfcmVjb3Jkc19zZXJ2aWNlIl19.A9afo01sTFGKaAp96v19PlC5-eBx1q_VBt3us-f55wR2kssLH0K-iS-hRUKDBGPk6LwvYP3FACFUODRz19o2d1DNTJXdko6t8Fl2KGu5f4PCN0_TWwMrCCUVrhaIXdLiIwB_a-sG_pe11MuK9JFpzJ85WKuJ6SmTx_ugOhXVvkK-pyxa9Htdf07lQsykg6oMWXhnhNw08X8V8lkvuTpe9wnXWq3FPWUHp4ZRDxq6X3xr1dwQi8F1O9AgsPwqRCEDd8lsdBTK7_XSrNqt6YPtDbI9zTuw_K4l0yo-gsIDZpr9gcz9VrL4hPki7C3nPRwH40l5n9GSx4dvo9nj62pVOA

{
    "first_name": "Test",
    "last_name": "Patient",
    "surname": "Default",
    "email": "ftp@gmail.com",
    "phone": "254700000000",
    "id_number":"12345678"
}

###
DELETE http://127.0.0.1:8000/patients/565b22b0-d334-42de-a162-bef4fd73bf1f/
Content-Type: application/json
Authorization: Token eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQzNzg2ODI0LCJpYXQiOjE3NDM3ODUwMjQsImp0aSI6ImE3YzFiM2ZjMTRkMTRhZjNiODNiM2I2NTk5YWUzYTk1IiwidXNlcl9pZCI6IjBhMjBjYzA0LTMzMzAtNDEwYy05ZTFjLTg3MzczMjhkNTE0MCIsImlzX3N1cGVydXNlciI6ZmFsc2UsImlzX3N0YWZmIjpmYWxzZSwiaXNfYWN0aXZlIjp0cnVlLCJwYXRpZW50X2lkIjoiMGEyMGNjMDQtMzMzMC00MTBjLTllMWMtODczNzMyOGQ1MTQwIiwiaXNzIjoidXNlcl9zZXJ2aWNlIiwiYXVkIjpbImFwcG9pbnRtZW50X3NlcnZpY2UiLCJkb2N0b3Jfc2VydmljZSIsIm1lZGljYWxfcmVjb3Jkc19zZXJ2aWNlIl19.A9afo01sTFGKaAp96v19PlC5-eBx1q_VBt3us-f55wR2kssLH0K-iS-hRUKDBGPk6LwvYP3FACFUODRz19o2d1DNTJXdko6t8Fl2KGu5f4PCN0_TWwMrCCUVrhaIXdLiIwB_a-sG_pe11MuK9JFpzJ85WKuJ6SmTx_ugOhXVvkK-pyxa9Htdf07lQsykg6oMWXhnhNw08X8V8lkvuTpe9wnXWq3FPWUHp4ZRDxq6X3xr1dwQi8F1O9AgsPwqRCEDd8lsdBTK7_XSrNqt6YPtDbI9zTuw_K4l0yo-gsIDZpr9gcz9VrL4hPki7C3nPRwH40l5n9GSx4dvo9nj62pVOA

###
GET http://127.0.0.1:8000/patients/0a20cc04-3330-410c-9e1c-8737328d5140/
Content-Type: application/json
Authorization: Token eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQzNzg2ODI0LCJpYXQiOjE3NDM3ODUwMjQsImp0aSI6ImE3YzFiM2ZjMTRkMTRhZjNiODNiM2I2NTk5YWUzYTk1IiwidXNlcl9pZCI6IjBhMjBjYzA0LTMzMzAtNDEwYy05ZTFjLTg3MzczMjhkNTE0MCIsImlzX3N1cGVydXNlciI6ZmFsc2UsImlzX3N0YWZmIjpmYWxzZSwiaXNfYWN0aXZlIjp0cnVlLCJwYXRpZW50X2lkIjoiMGEyMGNjMDQtMzMzMC00MTBjLTllMWMtODczNzMyOGQ1MTQwIiwiaXNzIjoidXNlcl9zZXJ2aWNlIiwiYXVkIjpbImFwcG9pbnRtZW50X3NlcnZpY2UiLCJkb2N0b3Jfc2VydmljZSIsIm1lZGljYWxfcmVjb3Jkc19zZXJ2aWNlIl19.A9afo01sTFGKaAp96v19PlC5-eBx1q_VBt3us-f55wR2kssLH0K-iS-hRUKDBGPk6LwvYP3FACFUODRz19o2d1DNTJXdko6t8Fl2KGu5f4PCN0_TWwMrCCUVrhaIXdLiIwB_a-sG_pe11MuK9JFpzJ85WKuJ6SmTx_ugOhXVvkK-pyxa9Htdf07lQsykg6oMWXhnhNw08X8V8lkvuTpe9wnXWq3FPWUHp4ZRDxq6X3xr1dwQi8F1O9AgsPwqRCEDd8lsdBTK7_XSrNqt6YPtDbI9zTuw_K4l0yo-gsIDZpr9gcz9VrL4hPki7C3nPRwH40l5n9GSx4dvo9nj62pVOA

###
GET http://127.0.0.1:8000/patients/me/
Content-Type: application/json
Authorization: Token eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQzNzg2ODI0LCJpYXQiOjE3NDM3ODUwMjQsImp0aSI6ImE3YzFiM2ZjMTRkMTRhZjNiODNiM2I2NTk5YWUzYTk1IiwidXNlcl9pZCI6IjBhMjBjYzA0LTMzMzAtNDEwYy05ZTFjLTg3MzczMjhkNTE0MCIsImlzX3N1cGVydXNlciI6ZmFsc2UsImlzX3N0YWZmIjpmYWxzZSwiaXNfYWN0aXZlIjp0cnVlLCJwYXRpZW50X2lkIjoiMGEyMGNjMDQtMzMzMC00MTBjLTllMWMtODczNzMyOGQ1MTQwIiwiaXNzIjoidXNlcl9zZXJ2aWNlIiwiYXVkIjpbImFwcG9pbnRtZW50X3NlcnZpY2UiLCJkb2N0b3Jfc2VydmljZSIsIm1lZGljYWxfcmVjb3Jkc19zZXJ2aWNlIl19.A9afo01sTFGKaAp96v19PlC5-eBx1q_VBt3us-f55wR2kssLH0K-iS-hRUKDBGPk6LwvYP3FACFUODRz19o2d1DNTJXdko6t8Fl2KGu5f4PCN0_TWwMrCCUVrhaIXdLiIwB_a-sG_pe11MuK9JFpzJ85WKuJ6SmTx_ugOhXVvkK-pyxa9Htdf07lQsykg6oMWXhnhNw08X8V8lkvuTpe9wnXWq3FPWUHp4ZRDxq6X3xr1dwQi8F1O9AgsPwqRCEDd8lsdBTK7_XSrNqt6YPtDbI9zTuw_K4l0yo-gsIDZpr9gcz9VrL4hPki7C3nPRwH40l5n9GSx4dvo9nj62pVOA

###
PUT http://127.0.0.1:8000/patients/me/password/
Content-Type: application/json
Authorization: Token eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQzNzg2ODI0LCJpYXQiOjE3NDM3ODUwMjQsImp0aSI6ImE3YzFiM2ZjMTRkMTRhZjNiODNiM2I2NTk5YWUzYTk1IiwidXNlcl9pZCI6IjBhMjBjYzA0LTMzMzAtNDEwYy05ZTFjLTg3MzczMjhkNTE0MCIsImlzX3N1cGVydXNlciI6ZmFsc2UsImlzX3N0YWZmIjpmYWxzZSwiaXNfYWN0aXZlIjp0cnVlLCJwYXRpZW50X2lkIjoiMGEyMGNjMDQtMzMzMC00MTBjLTllMWMtODczNzMyOGQ1MTQwIiwiaXNzIjoidXNlcl9zZXJ2aWNlIiwiYXVkIjpbImFwcG9pbnRtZW50X3NlcnZpY2UiLCJkb2N0b3Jfc2VydmljZSIsIm1lZGljYWxfcmVjb3Jkc19zZXJ2aWNlIl19.A9afo01sTFGKaAp96v19PlC5-eBx1q_VBt3us-f55wR2kssLH0K-iS-hRUKDBGPk6LwvYP3FACFUODRz19o2d1DNTJXdko6t8Fl2KGu5f4PCN0_TWwMrCCUVrhaIXdLiIwB_a-sG_pe11MuK9JFpzJ85WKuJ6SmTx_ugOhXVvkK-pyxa9Htdf07lQsykg6oMWXhnhNw08X8V8lkvuTpe9wnXWq3FPWUHp4ZRDxq6X3xr1dwQi8F1O9AgsPwqRCEDd8lsdBTK7_XSrNqt6YPtDbI9zTuw_K4l0yo-gsIDZpr9gcz9VrL4hPki7C3nPRwH40l5n9GSx4dvo9nj62pVOA

{
    "old_password":"Admin@@1",
    "new_password":"Patient@@1"
}

###
GET http://127.0.0.1:8000/patients/status/0a20cc04-3330-410c-9e1c-8737328d5140/
Content-Type: application/json
Authorization: Token eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQzNzg2ODI0LCJpYXQiOjE3NDM3ODUwMjQsImp0aSI6ImE3YzFiM2ZjMTRkMTRhZjNiODNiM2I2NTk5YWUzYTk1IiwidXNlcl9pZCI6IjBhMjBjYzA0LTMzMzAtNDEwYy05ZTFjLTg3MzczMjhkNTE0MCIsImlzX3N1cGVydXNlciI6ZmFsc2UsImlzX3N0YWZmIjpmYWxzZSwiaXNfYWN0aXZlIjp0cnVlLCJwYXRpZW50X2lkIjoiMGEyMGNjMDQtMzMzMC00MTBjLTllMWMtODczNzMyOGQ1MTQwIiwiaXNzIjoidXNlcl9zZXJ2aWNlIiwiYXVkIjpbImFwcG9pbnRtZW50X3NlcnZpY2UiLCJkb2N0b3Jfc2VydmljZSIsIm1lZGljYWxfcmVjb3Jkc19zZXJ2aWNlIl19.A9afo01sTFGKaAp96v19PlC5-eBx1q_VBt3us-f55wR2kssLH0K-iS-hRUKDBGPk6LwvYP3FACFUODRz19o2d1DNTJXdko6t8Fl2KGu5f4PCN0_TWwMrCCUVrhaIXdLiIwB_a-sG_pe11MuK9JFpzJ85WKuJ6SmTx_ugOhXVvkK-pyxa9Htdf07lQsykg6oMWXhnhNw08X8V8lkvuTpe9wnXWq3FPWUHp4ZRDxq6X3xr1dwQi8F1O9AgsPwqRCEDd8lsdBTK7_XSrNqt6YPtDbI9zTuw_K4l0yo-gsIDZpr9gcz9VrL4hPki7C3nPRwH40l5n9GSx4dvo9nj62pVOA

{
    "is_active": true
}