# Generated by Django 5.1.7 on 2025-04-23 11:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('prognosis', models.TextField()),
                ('age', models.IntegerField()),
                ('height_m', models.FloatField(help_text='Height in metres')),
                ('weight_kg', models.FloatField(help_text='Weight in kilograms')),
                ('hiv_status', models.SmallIntegerField(choices=[(0, 'negative'), (1, 'positive')])),
                ('blood_group', models.SmallIntegerField(choices=[(0, 'A+'), (1, 'A-'), (2, 'B+'), (3, 'B-'), (4, 'AB+'), (5, 'AB-'), (6, 'O-'), (7, 'O+')])),
                ('body_temperature', models.IntegerField()),
                ('systolic_bp', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('diastolic_bp', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('details', models.TextField(blank=True, null=True)),
                ('result', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RecordOwnership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('doctor_id', models.UUIDField(blank=True, null=True)),
                ('patient_id', models.UUIDField(blank=True, null=True)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.medicalrecord')),
            ],
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='tests',
            field=models.ManyToManyField(related_name='medical_records', to='app.test'),
        ),
    ]
