# Generated by Django 5.1.7 on 2025-04-10 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicalrecord',
            old_name='updated_ad',
            new_name='updated_at',
        ),
    ]
