# Generated by Django 5.1.7 on 2025-04-25 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicalrecord',
            old_name='height_m',
            new_name='height_cm',
        ),
    ]
