# Generated by Django 5.1.7 on 2025-04-10 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_updated_ad_medicalrecord_updated_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test',
            old_name='updated_ad',
            new_name='updated_at',
        ),
    ]
