# Generated by Django 5.1.7 on 2025-04-10 17:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_updated_ad_test_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecordOwnership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('doctor_id', models.UUIDField(blank=True)),
                ('patient_id', models.UUIDField(blank=True)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.medicalrecord')),
            ],
        ),
    ]
