POST http://127.0.0.1:8000/api/v1/patients/login/
Content-Type: application/json

{
    "email":"johndoe@gmail.com",
    "password": "Patient@@1"
}


###
GET http://127.0.0.1:8000/api/v1/patients/
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ3NTk3Mzg0LCJpYXQiOjE3NDc1OTU1ODQsImp0aSI6IjFiMzViYjU2YmJjZTQ1MTZhZjYyMDc3ZDA2YzUzMjlhIiwidXNlcl9pZCI6IjAzNzRiMjkxLWQ4NDUtNDkzNS1hMzdkLTg2ZGQ4ODU0MzIxOCIsImlzX3N1cGVydXNlciI6ZmFsc2UsImlzX3N0YWZmIjpmYWxzZSwiaXNfYWN0aXZlIjp0cnVlLCJpc3MiOiJwYXRpZW50X3NlcnZpY2UiLCJhdWQiOlsiYXBwb2ludG1lbnRfc2VydmljZSIsImRvY3Rvcl9zZXJ2aWNlIiwibWVkaWNhbF9yZWNvcmRzX3NlcnZpY2UiXSwicm9sZSI6InBhdGllbnQifQ.Dji5qp1GhJkkqO1BGXD5AKgjie02BWcmMaDvqTaC7HhfA-S4IYSQ8AFjpPBAoV890XG2Yl06D7N70XwmaUXgWm1iin_lY5t327zjH6Lj--JvKnDekpzpF1LNbptYaYoWpe7pLTUjut7iSzvQo1x7J1nNcAkWx4mW0lD0D2xfl_uZqW2LR-yFxYKcn7eSMceLFM6Zjg5zQIe4UAFNVZh7yhmBh2uyobRJ1UZbKvwxclT7I72CTT5mNP8xoAcELawWSrBr3ACK9XHKlTOkbJ_sfMe-30DUJw_egbRqdwWxCXLqD2KzFMUDAFgw3jGUPOxY9qhCdQDt31Qyr226jju2wA

###
POST http://127.0.0.1:8000/api/v1/patients/
Content-Type: application/json

{
    "first_name":"Lenny",
    "last_name":"Wamunyoro",
    "surname":"Gachagua",
    "email":"lenaealf@gmail.com",
    "password":"Patient@@1",
    "phone":"254700000005",
    "id_number":"12345675",
    "residence": "Langas, Eldoret",
    "occupation": "Farmer",
    "gender":0,
    "next_of_kin":{
        "first_name":"Annet",
        "last_name":"Chebet",
        "phone":"254722112212",
        "relationship":"Wife",
        "email":"annetchebet@wife.email"
    }
}
###
PUT  http://127.0.0.1:8000/api/v1/patients/selfupdate/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ3NDE1ODQ1LCJpYXQiOjE3NDc0MTQwNDUsImp0aSI6IjE0MDdhNDI2ZWI0MDQyMmJiMTY4M2ZmMThmMjE4ZTQ4IiwidXNlcl9pZCI6IjAzNzRiMjkxLWQ4NDUtNDkzNS1hMzdkLTg2ZGQ4ODU0MzIxOCIsImlzX3N1cGVydXNlciI6ZmFsc2UsImlzX3N0YWZmIjpmYWxzZSwiaXNfYWN0aXZlIjp0cnVlLCJpc3MiOiJwYXRpZW50X3NlcnZpY2UiLCJhdWQiOlsiYXBwb2ludG1lbnRfc2VydmljZSIsImRvY3Rvcl9zZXJ2aWNlIiwibWVkaWNhbF9yZWNvcmRzX3NlcnZpY2UiXSwicm9sZSI6InBhdGllbnQifQ.COYXQBXChq8W1VHAvdZx8wCOCOylk7-HcyfRIRcnGvPAUTfqC5bq2tClIV5zSTwbZa4wmIbzfecZ3HkXoVRZ_ouU4dDkF8538-NCyA5dqvBTsHQJZyReeIrlh0S85hZPMErKWopb3Vy3uFD9l-P7vufB2AlinS3gMOgi9ma5bgsHmrKYs9AiksYNcP66TRf2BdgZaqIHD5CQjEvAa5jTgDFYO2InACcFE1vfVJbUenx9CvFJyuv1B64A17b4RBQvGzv-EKL8ebGUk8jaSyZVDjfbaPP7ZgVtEbV-xRCjzMML0jqk6Bz-1ekyOYjnEfz06__S-ylvywicHGWuozOcrA

{
    "first_name":"Johana",
    "last_name":"Doe",
    "surname":"Smith",
    "email":"johndoe@gmail.com",
    "password":"Patient@@1",
    "phone":"254700000000",
    "id_number":"12345678",
    "residence": "Kirigiti, Kiambu",
    "occupation": "plumber",
    "gender":0,
    "next_of_kin": {
        "first_name":"Princess",
        "last_name":"Rupanzel",
        "email":"nok@email.com",
        "phone":"254711111111",
        "relationship":"daughter"
    }
}
###
GET http://127.0.0.1:8000/api/v1/patients/4aeff20e-9c2a-4ef4-a7fa-b4bb738bcc23/
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ3MDUzNDI3LCJpYXQiOjE3NDcwNTE2MjcsImp0aSI6ImQ4YmM0MDU1YWVkYzQxNGI5ZTc5ZTAzODFlM2NkY2NjIiwidXNlcl9pZCI6IjAzNzRiMjkxLWQ4NDUtNDkzNS1hMzdkLTg2ZGQ4ODU0MzIxOCIsImlzX3N1cGVydXNlciI6ZmFsc2UsImlzX3N0YWZmIjpmYWxzZSwiaXNfYWN0aXZlIjp0cnVlLCJpc3MiOiJwYXRpZW50X3NlcnZpY2UiLCJhdWQiOlsiYXBwb2ludG1lbnRfc2VydmljZSIsImRvY3Rvcl9zZXJ2aWNlIiwibWVkaWNhbF9yZWNvcmRzX3NlcnZpY2UiXSwicm9sZSI6InBhdGllbnQifQ.IuIs-EOjO3lasRihNAGjM9J34IlDGCY_AysXqWVSmCXOXj_lIwStgcMF9o7BgPXmhTT1TmQS6-DEwi4MOgqSzOReyWnBiU4vXS7DY5NABurBqck8-m-LwgIq6636fFA2JfoRhVDNkjXWq6HSWRcO0pCUbQqFO3S3os0P4TJq4hxQD7v_N_g_fige2dlW3mImT1zAqCK6WjKpWAKOaXryIS9Ly-PSLr02DDShIxxt4C3D39R56tIIjSA3bEiHMbqIuVPOybT5dDnpeLxXdng_KS13qReuO5vzr0haiIcjH52vSBmbxP9mEBowMkhTrwo2uLUjkc5qEHEeNRxsyFltmw


###
GET http://127.0.0.1:8000/api/v1/auth/me/
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ3NDE1ODQ1LCJpYXQiOjE3NDc0MTQwNDUsImp0aSI6IjE0MDdhNDI2ZWI0MDQyMmJiMTY4M2ZmMThmMjE4ZTQ4IiwidXNlcl9pZCI6IjAzNzRiMjkxLWQ4NDUtNDkzNS1hMzdkLTg2ZGQ4ODU0MzIxOCIsImlzX3N1cGVydXNlciI6ZmFsc2UsImlzX3N0YWZmIjpmYWxzZSwiaXNfYWN0aXZlIjp0cnVlLCJpc3MiOiJwYXRpZW50X3NlcnZpY2UiLCJhdWQiOlsiYXBwb2ludG1lbnRfc2VydmljZSIsImRvY3Rvcl9zZXJ2aWNlIiwibWVkaWNhbF9yZWNvcmRzX3NlcnZpY2UiXSwicm9sZSI6InBhdGllbnQifQ.COYXQBXChq8W1VHAvdZx8wCOCOylk7-HcyfRIRcnGvPAUTfqC5bq2tClIV5zSTwbZa4wmIbzfecZ3HkXoVRZ_ouU4dDkF8538-NCyA5dqvBTsHQJZyReeIrlh0S85hZPMErKWopb3Vy3uFD9l-P7vufB2AlinS3gMOgi9ma5bgsHmrKYs9AiksYNcP66TRf2BdgZaqIHD5CQjEvAa5jTgDFYO2InACcFE1vfVJbUenx9CvFJyuv1B64A17b4RBQvGzv-EKL8ebGUk8jaSyZVDjfbaPP7ZgVtEbV-xRCjzMML0jqk6Bz-1ekyOYjnEfz06__S-ylvywicHGWuozOcrA

###
PUT http://127.0.0.1:8000/api/v1/auth/changepassword/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ3NDk4ODE2LCJpYXQiOjE3NDc0OTcwMTYsImp0aSI6IjVhM2MzOGEzOTZiMzQ1OTE4MTI2ZTNmYTdmZTgyYzQ1IiwidXNlcl9pZCI6IjAzNzRiMjkxLWQ4NDUtNDkzNS1hMzdkLTg2ZGQ4ODU0MzIxOCIsImlzX3N1cGVydXNlciI6ZmFsc2UsImlzX3N0YWZmIjpmYWxzZSwiaXNfYWN0aXZlIjp0cnVlLCJpc3MiOiJwYXRpZW50X3NlcnZpY2UiLCJhdWQiOlsiYXBwb2ludG1lbnRfc2VydmljZSIsImRvY3Rvcl9zZXJ2aWNlIiwibWVkaWNhbF9yZWNvcmRzX3NlcnZpY2UiXSwicm9sZSI6InBhdGllbnQifQ.cGYznBw4pnQ2bkMdAthu3rjjljmycTA1Ib44R9ei9AUjlLrKwBKI7t43WZTb8vLdBGY3sRih7sKWnHGCxPqbkK27H8fFZ575jVSU1eQZ0lz7RifGcMgTqWw9y88Z_C5BOmtOLwujwf8ADKC9z4YrQ223-g_rvw_m2bwG2J1asNZqlplDdYHACSpUPgJrldrh3vKAJtSDq1WTbJ7X10mJcESQtSak-0T_bQgZuDMOObUwEqPnHfZLCK4MySKhO435bGWqJ_y9iJbqZtVfedMBInKsKz3m9TiUyOV_jznzA-MEguqCJZ4FSu5S2S8mL8BX0myl1Us1T-aMAyx2ZhDygg

{
    "old_password":"Admin@@1",
    "new_password":"Patient@@1"
}


###
PUT http://127.0.0.1:8000/api/v1/patients/0f19b5c2-0633-4d36-a458-3d0d9fc8929d/resetpassword/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ3NTk3Mzg0LCJpYXQiOjE3NDc1OTU1ODQsImp0aSI6IjFiMzViYjU2YmJjZTQ1MTZhZjYyMDc3ZDA2YzUzMjlhIiwidXNlcl9pZCI6IjAzNzRiMjkxLWQ4NDUtNDkzNS1hMzdkLTg2ZGQ4ODU0MzIxOCIsImlzX3N1cGVydXNlciI6ZmFsc2UsImlzX3N0YWZmIjpmYWxzZSwiaXNfYWN0aXZlIjp0cnVlLCJpc3MiOiJwYXRpZW50X3NlcnZpY2UiLCJhdWQiOlsiYXBwb2ludG1lbnRfc2VydmljZSIsImRvY3Rvcl9zZXJ2aWNlIiwibWVkaWNhbF9yZWNvcmRzX3NlcnZpY2UiXSwicm9sZSI6InBhdGllbnQifQ.Dji5qp1GhJkkqO1BGXD5AKgjie02BWcmMaDvqTaC7HhfA-S4IYSQ8AFjpPBAoV890XG2Yl06D7N70XwmaUXgWm1iin_lY5t327zjH6Lj--JvKnDekpzpF1LNbptYaYoWpe7pLTUjut7iSzvQo1x7J1nNcAkWx4mW0lD0D2xfl_uZqW2LR-yFxYKcn7eSMceLFM6Zjg5zQIe4UAFNVZh7yhmBh2uyobRJ1UZbKvwxclT7I72CTT5mNP8xoAcELawWSrBr3ACK9XHKlTOkbJ_sfMe-30DUJw_egbRqdwWxCXLqD2KzFMUDAFgw3jGUPOxY9qhCdQDt31Qyr226jju2wA

{
    "new_password":"Patient@@1"
}

###

DELETE http://127.0.0.1:8000/api/v1/patients/82844eb4-a215-4af2-a13a-4030758e644c/
Authorization: Token eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ3MzM2ODc2LCJpYXQiOjE3NDczMzUwNzYsImp0aSI6Ijg0ZTQ1OWZlN2Y4NjQ4MThiOWNkN2RmYWU4YjZlNTA1IiwidXNlcl9pZCI6IjAzNzRiMjkxLWQ4NDUtNDkzNS1hMzdkLTg2ZGQ4ODU0MzIxOCIsImlzX3N1cGVydXNlciI6ZmFsc2UsImlzX3N0YWZmIjpmYWxzZSwiaXNfYWN0aXZlIjp0cnVlLCJpc3MiOiJwYXRpZW50X3NlcnZpY2UiLCJhdWQiOlsiYXBwb2ludG1lbnRfc2VydmljZSIsImRvY3Rvcl9zZXJ2aWNlIiwibWVkaWNhbF9yZWNvcmRzX3NlcnZpY2UiXSwicm9sZSI6InBhdGllbnQifQ.Tva9YsKudawzPH9aBw9eUre8sGA-XIuKkPoYxbBWBg3XYMDjP0oQzpsFYY8Ikct8Wq8WlqYpKbWMyDWR0PzWBZ12qSTPvzV4_wWK059FHAD5o-7H7wcnEfC0lPEgllKyAdqJoAZnso2BsRRl-P0Rknx0cfobSPSl4MOLWtf6_eGOOxs8nLT6WNR7hgvHgq8e8Mc1FLUI4bmDSp5N1BacWiizf5QNg1gSjFVezel67Oa4hS8XCKADypYeYQINDm6x6ZOLYrHqkatoDHjLOD8TuXktFRkceYluQ-1nhAI7nQ9Q5_mYSSaolxh7v7pcF6XvwaB8TdBTuZqrYlRp4kq_Mw

###
PUT http://127.0.0.1:8000/api/v1/patients/
Content-Type: application/json
Authorization: Token eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ3MzM2ODc2LCJpYXQiOjE3NDczMzUwNzYsImp0aSI6Ijg0ZTQ1OWZlN2Y4NjQ4MThiOWNkN2RmYWU4YjZlNTA1IiwidXNlcl9pZCI6IjAzNzRiMjkxLWQ4NDUtNDkzNS1hMzdkLTg2ZGQ4ODU0MzIxOCIsImlzX3N1cGVydXNlciI6ZmFsc2UsImlzX3N0YWZmIjpmYWxzZSwiaXNfYWN0aXZlIjp0cnVlLCJpc3MiOiJwYXRpZW50X3NlcnZpY2UiLCJhdWQiOlsiYXBwb2ludG1lbnRfc2VydmljZSIsImRvY3Rvcl9zZXJ2aWNlIiwibWVkaWNhbF9yZWNvcmRzX3NlcnZpY2UiXSwicm9sZSI6InBhdGllbnQifQ.Tva9YsKudawzPH9aBw9eUre8sGA-XIuKkPoYxbBWBg3XYMDjP0oQzpsFYY8Ikct8Wq8WlqYpKbWMyDWR0PzWBZ12qSTPvzV4_wWK059FHAD5o-7H7wcnEfC0lPEgllKyAdqJoAZnso2BsRRl-P0Rknx0cfobSPSl4MOLWtf6_eGOOxs8nLT6WNR7hgvHgq8e8Mc1FLUI4bmDSp5N1BacWiizf5QNg1gSjFVezel67Oa4hS8XCKADypYeYQINDm6x6ZOLYrHqkatoDHjLOD8TuXktFRkceYluQ-1nhAI7nQ9Q5_mYSSaolxh7v7pcF6XvwaB8TdBTuZqrYlRp4kq_Mw

{
    "first_name":"Alfred",
    "last_name":"Lenae",
    "surname":"Raztaf",
    "email":"lenaealf@gmail.com",
    "password":"Patient@@1",
    "phone":"254700000002",
    "id_number":"12345675",
    "residence": "Ukunda, Kwale",
    "occupation": "Fisherman",
    "gender":0,
    "next_of_kin":{
        "first_name":"Mwanaisha",
        "last_name":"Latifa",
        "phone":"254722112212",
        "relationship":"Wife",
        "email":"latifamwanaisha@opp.email"
    }
}


###
GET http://127.0.0.1:8003/appointments/
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ3MDUzNDI3LCJpYXQiOjE3NDcwNTE2MjcsImp0aSI6ImQ4YmM0MDU1YWVkYzQxNGI5ZTc5ZTAzODFlM2NkY2NjIiwidXNlcl9pZCI6IjAzNzRiMjkxLWQ4NDUtNDkzNS1hMzdkLTg2ZGQ4ODU0MzIxOCIsImlzX3N1cGVydXNlciI6ZmFsc2UsImlzX3N0YWZmIjpmYWxzZSwiaXNfYWN0aXZlIjp0cnVlLCJpc3MiOiJwYXRpZW50X3NlcnZpY2UiLCJhdWQiOlsiYXBwb2ludG1lbnRfc2VydmljZSIsImRvY3Rvcl9zZXJ2aWNlIiwibWVkaWNhbF9yZWNvcmRzX3NlcnZpY2UiXSwicm9sZSI6InBhdGllbnQifQ.IuIs-EOjO3lasRihNAGjM9J34IlDGCY_AysXqWVSmCXOXj_lIwStgcMF9o7BgPXmhTT1TmQS6-DEwi4MOgqSzOReyWnBiU4vXS7DY5NABurBqck8-m-LwgIq6636fFA2JfoRhVDNkjXWq6HSWRcO0pCUbQqFO3S3os0P4TJq4hxQD7v_N_g_fige2dlW3mImT1zAqCK6WjKpWAKOaXryIS9Ly-PSLr02DDShIxxt4C3D39R56tIIjSA3bEiHMbqIuVPOybT5dDnpeLxXdng_KS13qReuO5vzr0haiIcjH52vSBmbxP9mEBowMkhTrwo2uLUjkc5qEHEeNRxsyFltmw

###
GET http://127.0.0.1:8006/patients/0374b291-d845-4935-a37d-86dd88543218/
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ3MDUzNDI3LCJpYXQiOjE3NDcwNTE2MjcsImp0aSI6ImQ4YmM0MDU1YWVkYzQxNGI5ZTc5ZTAzODFlM2NkY2NjIiwidXNlcl9pZCI6IjAzNzRiMjkxLWQ4NDUtNDkzNS1hMzdkLTg2ZGQ4ODU0MzIxOCIsImlzX3N1cGVydXNlciI6ZmFsc2UsImlzX3N0YWZmIjpmYWxzZSwiaXNfYWN0aXZlIjp0cnVlLCJpc3MiOiJwYXRpZW50X3NlcnZpY2UiLCJhdWQiOlsiYXBwb2ludG1lbnRfc2VydmljZSIsImRvY3Rvcl9zZXJ2aWNlIiwibWVkaWNhbF9yZWNvcmRzX3NlcnZpY2UiXSwicm9sZSI6InBhdGllbnQifQ.IuIs-EOjO3lasRihNAGjM9J34IlDGCY_AysXqWVSmCXOXj_lIwStgcMF9o7BgPXmhTT1TmQS6-DEwi4MOgqSzOReyWnBiU4vXS7DY5NABurBqck8-m-LwgIq6636fFA2JfoRhVDNkjXWq6HSWRcO0pCUbQqFO3S3os0P4TJq4hxQD7v_N_g_fige2dlW3mImT1zAqCK6WjKpWAKOaXryIS9Ly-PSLr02DDShIxxt4C3D39R56tIIjSA3bEiHMbqIuVPOybT5dDnpeLxXdng_KS13qReuO5vzr0haiIcjH52vSBmbxP9mEBowMkhTrwo2uLUjkc5qEHEeNRxsyFltmw

###
GET http://localhost:8000/records/doctors/records/
Authorization: Token eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ1NjAwNTMyLCJpYXQiOjE3NDU1OTY5MzIsImp0aSI6IjgwNGY5OWY5ZjMwYTQyOWRhNThjMjNkNmJhNTUzNzVhIiwidXNlcl9pZCI6IjRmYTE2N2FjLTgzMDQtNGYyYS05M2M3LTViMmZkYzMyMDdjNyIsImlzX3N1cGVydXNlciI6ZmFsc2UsImlzX3N0YWZmIjpmYWxzZSwiaXNfYWN0aXZlIjp0cnVlLCJpc3MiOiJkb2N0b3Jfc2VydmljZSIsImF1ZCI6WyJwYXRpZW50X3NlcnZpY2UiLCJtZWRpY2FsX3JlY29yZHNfc2VydmljZSIsImFwcG9pbnRtZW50X3NlcnZpY2UiXSwicm9sZSI6ImRvY3RvciJ9.hAV4F-AS9ITK5Rsaz-BgPRt-jD-JiYQF5DwgBQlMuyy3JwY8YXv4VFzRL8MKf8IM23hxYrVqbgwUT3YVKXT1VTBgRK5XGVETHYANqPYGlsbECQpc82__nCwkFo7dx_3YhotYuPMGkN1JDOCzrAmE9p-LR4hRugrjbl_VHwCzoa_fGuGFwBxQ7BJLQQ_2WjBTb3GNKTFxcyl38GSijBjF7BOB29-4t9BrBfcp6GkqR2UX8JkSHCZhDNGrwvjx-XNariKoziq2DZqfetuJs9Vby5pyCZeQ8Qx4-jr5ZEJgnx58GpsXETc7ebFTtyUPz0QA2PGsAPEOogE7tDSphvyuWA



###
POST http://localhost:8000/records/licensing/records/
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Length: 123
Authorization: Bearer

{
    
}