POST http://127.0.0.1:8000/api/v1/patients/login/
Content-Type: application/json

{
    "email":"johndoe@gmail.com",
    "password": "Patient@@1"
}


###
GET http://127.0.0.1:8000/api/v1/patients/
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ3MDUzNDI3LCJpYXQiOjE3NDcwNTE2MjcsImp0aSI6ImQ4YmM0MDU1YWVkYzQxNGI5ZTc5ZTAzODFlM2NkY2NjIiwidXNlcl9pZCI6IjAzNzRiMjkxLWQ4NDUtNDkzNS1hMzdkLTg2ZGQ4ODU0MzIxOCIsImlzX3N1cGVydXNlciI6ZmFsc2UsImlzX3N0YWZmIjpmYWxzZSwiaXNfYWN0aXZlIjp0cnVlLCJpc3MiOiJwYXRpZW50X3NlcnZpY2UiLCJhdWQiOlsiYXBwb2ludG1lbnRfc2VydmljZSIsImRvY3Rvcl9zZXJ2aWNlIiwibWVkaWNhbF9yZWNvcmRzX3NlcnZpY2UiXSwicm9sZSI6InBhdGllbnQifQ.IuIs-EOjO3lasRihNAGjM9J34IlDGCY_AysXqWVSmCXOXj_lIwStgcMF9o7BgPXmhTT1TmQS6-DEwi4MOgqSzOReyWnBiU4vXS7DY5NABurBqck8-m-LwgIq6636fFA2JfoRhVDNkjXWq6HSWRcO0pCUbQqFO3S3os0P4TJq4hxQD7v_N_g_fige2dlW3mImT1zAqCK6WjKpWAKOaXryIS9Ly-PSLr02DDShIxxt4C3D39R56tIIjSA3bEiHMbqIuVPOybT5dDnpeLxXdng_KS13qReuO5vzr0haiIcjH52vSBmbxP9mEBowMkhTrwo2uLUjkc5qEHEeNRxsyFltmw

###
GET http://127.0.0.1:8000/api/v1/patients/0374b291-d845-4935-a37d-86dd88543218/
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ3MDUzNDI3LCJpYXQiOjE3NDcwNTE2MjcsImp0aSI6ImQ4YmM0MDU1YWVkYzQxNGI5ZTc5ZTAzODFlM2NkY2NjIiwidXNlcl9pZCI6IjAzNzRiMjkxLWQ4NDUtNDkzNS1hMzdkLTg2ZGQ4ODU0MzIxOCIsImlzX3N1cGVydXNlciI6ZmFsc2UsImlzX3N0YWZmIjpmYWxzZSwiaXNfYWN0aXZlIjp0cnVlLCJpc3MiOiJwYXRpZW50X3NlcnZpY2UiLCJhdWQiOlsiYXBwb2ludG1lbnRfc2VydmljZSIsImRvY3Rvcl9zZXJ2aWNlIiwibWVkaWNhbF9yZWNvcmRzX3NlcnZpY2UiXSwicm9sZSI6InBhdGllbnQifQ.IuIs-EOjO3lasRihNAGjM9J34IlDGCY_AysXqWVSmCXOXj_lIwStgcMF9o7BgPXmhTT1TmQS6-DEwi4MOgqSzOReyWnBiU4vXS7DY5NABurBqck8-m-LwgIq6636fFA2JfoRhVDNkjXWq6HSWRcO0pCUbQqFO3S3os0P4TJq4hxQD7v_N_g_fige2dlW3mImT1zAqCK6WjKpWAKOaXryIS9Ly-PSLr02DDShIxxt4C3D39R56tIIjSA3bEiHMbqIuVPOybT5dDnpeLxXdng_KS13qReuO5vzr0haiIcjH52vSBmbxP9mEBowMkhTrwo2uLUjkc5qEHEeNRxsyFltmw


###
GET http://127.0.0.1:8000/api/v1/auth/me/
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ3MDUzNDI3LCJpYXQiOjE3NDcwNTE2MjcsImp0aSI6ImQ4YmM0MDU1YWVkYzQxNGI5ZTc5ZTAzODFlM2NkY2NjIiwidXNlcl9pZCI6IjAzNzRiMjkxLWQ4NDUtNDkzNS1hMzdkLTg2ZGQ4ODU0MzIxOCIsImlzX3N1cGVydXNlciI6ZmFsc2UsImlzX3N0YWZmIjpmYWxzZSwiaXNfYWN0aXZlIjp0cnVlLCJpc3MiOiJwYXRpZW50X3NlcnZpY2UiLCJhdWQiOlsiYXBwb2ludG1lbnRfc2VydmljZSIsImRvY3Rvcl9zZXJ2aWNlIiwibWVkaWNhbF9yZWNvcmRzX3NlcnZpY2UiXSwicm9sZSI6InBhdGllbnQifQ.IuIs-EOjO3lasRihNAGjM9J34IlDGCY_AysXqWVSmCXOXj_lIwStgcMF9o7BgPXmhTT1TmQS6-DEwi4MOgqSzOReyWnBiU4vXS7DY5NABurBqck8-m-LwgIq6636fFA2JfoRhVDNkjXWq6HSWRcO0pCUbQqFO3S3os0P4TJq4hxQD7v_N_g_fige2dlW3mImT1zAqCK6WjKpWAKOaXryIS9Ly-PSLr02DDShIxxt4C3D39R56tIIjSA3bEiHMbqIuVPOybT5dDnpeLxXdng_KS13qReuO5vzr0haiIcjH52vSBmbxP9mEBowMkhTrwo2uLUjkc5qEHEeNRxsyFltmw



###
GET http://127.0.0.1:8003/appointments/
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ3MDUzNDI3LCJpYXQiOjE3NDcwNTE2MjcsImp0aSI6ImQ4YmM0MDU1YWVkYzQxNGI5ZTc5ZTAzODFlM2NkY2NjIiwidXNlcl9pZCI6IjAzNzRiMjkxLWQ4NDUtNDkzNS1hMzdkLTg2ZGQ4ODU0MzIxOCIsImlzX3N1cGVydXNlciI6ZmFsc2UsImlzX3N0YWZmIjpmYWxzZSwiaXNfYWN0aXZlIjp0cnVlLCJpc3MiOiJwYXRpZW50X3NlcnZpY2UiLCJhdWQiOlsiYXBwb2ludG1lbnRfc2VydmljZSIsImRvY3Rvcl9zZXJ2aWNlIiwibWVkaWNhbF9yZWNvcmRzX3NlcnZpY2UiXSwicm9sZSI6InBhdGllbnQifQ.IuIs-EOjO3lasRihNAGjM9J34IlDGCY_AysXqWVSmCXOXj_lIwStgcMF9o7BgPXmhTT1TmQS6-DEwi4MOgqSzOReyWnBiU4vXS7DY5NABurBqck8-m-LwgIq6636fFA2JfoRhVDNkjXWq6HSWRcO0pCUbQqFO3S3os0P4TJq4hxQD7v_N_g_fige2dlW3mImT1zAqCK6WjKpWAKOaXryIS9Ly-PSLr02DDShIxxt4C3D39R56tIIjSA3bEiHMbqIuVPOybT5dDnpeLxXdng_KS13qReuO5vzr0haiIcjH52vSBmbxP9mEBowMkhTrwo2uLUjkc5qEHEeNRxsyFltmw

###
GET http://127.0.0.1:8006/patients/0374b291-d845-4935-a37d-86dd88543218/
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ3MDUzNDI3LCJpYXQiOjE3NDcwNTE2MjcsImp0aSI6ImQ4YmM0MDU1YWVkYzQxNGI5ZTc5ZTAzODFlM2NkY2NjIiwidXNlcl9pZCI6IjAzNzRiMjkxLWQ4NDUtNDkzNS1hMzdkLTg2ZGQ4ODU0MzIxOCIsImlzX3N1cGVydXNlciI6ZmFsc2UsImlzX3N0YWZmIjpmYWxzZSwiaXNfYWN0aXZlIjp0cnVlLCJpc3MiOiJwYXRpZW50X3NlcnZpY2UiLCJhdWQiOlsiYXBwb2ludG1lbnRfc2VydmljZSIsImRvY3Rvcl9zZXJ2aWNlIiwibWVkaWNhbF9yZWNvcmRzX3NlcnZpY2UiXSwicm9sZSI6InBhdGllbnQifQ.IuIs-EOjO3lasRihNAGjM9J34IlDGCY_AysXqWVSmCXOXj_lIwStgcMF9o7BgPXmhTT1TmQS6-DEwi4MOgqSzOReyWnBiU4vXS7DY5NABurBqck8-m-LwgIq6636fFA2JfoRhVDNkjXWq6HSWRcO0pCUbQqFO3S3os0P4TJq4hxQD7v_N_g_fige2dlW3mImT1zAqCK6WjKpWAKOaXryIS9Ly-PSLr02DDShIxxt4C3D39R56tIIjSA3bEiHMbqIuVPOybT5dDnpeLxXdng_KS13qReuO5vzr0haiIcjH52vSBmbxP9mEBowMkhTrwo2uLUjkc5qEHEeNRxsyFltmw

###
GET http://localhost:8000/records/doctors/records/
Authorization: Token eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ1NjAwNTMyLCJpYXQiOjE3NDU1OTY5MzIsImp0aSI6IjgwNGY5OWY5ZjMwYTQyOWRhNThjMjNkNmJhNTUzNzVhIiwidXNlcl9pZCI6IjRmYTE2N2FjLTgzMDQtNGYyYS05M2M3LTViMmZkYzMyMDdjNyIsImlzX3N1cGVydXNlciI6ZmFsc2UsImlzX3N0YWZmIjpmYWxzZSwiaXNfYWN0aXZlIjp0cnVlLCJpc3MiOiJkb2N0b3Jfc2VydmljZSIsImF1ZCI6WyJwYXRpZW50X3NlcnZpY2UiLCJtZWRpY2FsX3JlY29yZHNfc2VydmljZSIsImFwcG9pbnRtZW50X3NlcnZpY2UiXSwicm9sZSI6ImRvY3RvciJ9.hAV4F-AS9ITK5Rsaz-BgPRt-jD-JiYQF5DwgBQlMuyy3JwY8YXv4VFzRL8MKf8IM23hxYrVqbgwUT3YVKXT1VTBgRK5XGVETHYANqPYGlsbECQpc82__nCwkFo7dx_3YhotYuPMGkN1JDOCzrAmE9p-LR4hRugrjbl_VHwCzoa_fGuGFwBxQ7BJLQQ_2WjBTb3GNKTFxcyl38GSijBjF7BOB29-4t9BrBfcp6GkqR2UX8JkSHCZhDNGrwvjx-XNariKoziq2DZqfetuJs9Vby5pyCZeQ8Qx4-jr5ZEJgnx58GpsXETc7ebFTtyUPz0QA2PGsAPEOogE7tDSphvyuWA



###
POST http://localhost:8000/records/licensing/records/
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Length: 123
Authorization: Bearer

{
    
}