# Generated by Django 5.1.7 on 2025-05-04 17:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('user_id', models.CharField(max_length=255, unique=True)),
                ('face_img', models.ImageField(blank=True, null=True, upload_to='face_images/')),
                ('practicing_certificate', models.FileField(blank=True, null=True, upload_to='practicing_certificates/')),
                ('identity_card', models.FileField(blank=True, null=True, upload_to='id_cards/')),
                ('valid_practicing_certificate', models.BooleanField(default=False)),
                ('valid_identity_card', models.BooleanField(default=False)),
                ('valid_face_img', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'users',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['user_id'], name='users_user_id_83dd09_idx'), models.Index(fields=['created_at'], name='users_created_6541e9_idx')],
            },
        ),
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('status', models.IntegerField(choices=[(0, 'Pending'), (1, 'Approved'), (2, 'Disapproved'), (3, 'Suspended'), (4, 'Cancelled')], default=0)),
                ('expiration_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='license', to='app.user')),
            ],
            options={
                'verbose_name': 'License',
                'verbose_name_plural': 'Licenses',
                'db_table': 'licenses',
                'ordering': ['expiration_date'],
                'indexes': [models.Index(fields=['user_id'], name='licenses_user_id_ef0bbb_idx'), models.Index(fields=['expiration_date'], name='licenses_expirat_d1da69_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('expiration_date__gt', models.F('created_at'))), name='expiration_date_gt_created_at')],
            },
        ),
    ]
