# Generated by Django 5.1.7 on 2025-04-20 20:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DoctorCalender',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('doctor_id', models.CharField(unique=True)),
                ('weekday_shift_start', models.TimeField(default='09:00:00')),
                ('weekday_shift_end', models.TimeField(default='17:00:00')),
                ('weekday_break_start', models.TimeField(default='13:00:00')),
                ('weekday_break_duration', models.IntegerField(default=60)),
                ('weekend_shift_start', models.TimeField(default='10:00:00')),
                ('weekend_shift_end', models.TimeField(default='15:00:00')),
                ('weekend_break_start', models.TimeField(default='12:00:00')),
                ('weekend_break_duration', models.IntegerField(default=40)),
            ],
        ),
        migrations.CreateModel(
            name='OffPeriod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('doctor_id', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('start_time', models.TimeField(default='00:00:00')),
                ('end_time', models.TimeField(default='23:59:59')),
                ('nature', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('doctor_id', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('patient_id', models.CharField(max_length=100)),
                ('hospital_id', models.CharField(blank=True, max_length=100)),
                ('status', models.IntegerField(choices=[(0, 'pending'), (1, 'confirmed'), (2, 'done'), (3, 'missed')], default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.slot')),
            ],
        ),
    ]
