POST http://127.0.0.1:8003/medical-records/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ0MzE0NzczLCJpYXQiOjE3NDQzMTExNzMsImp0aSI6IjkwMzFmMjZkMzAzMjQ0ZWNhZWEyODdkYzJmYzg2ODQ2IiwidXNlcl9pZCI6IjBmOGI0NGZjLWU3Y2ItNDAwZi04ZDVkLTI1ZTIwYTUxYzI3ZCIsImlzX3N1cGVydXNlciI6ZmFsc2UsImlzX3N0YWZmIjpmYWxzZSwiaXNfYWN0aXZlIjp0cnVlLCJpc3MiOiJkb2N0b3Jfc2VydmljZSIsImF1ZCI6WyJwYXRpZW50X3NlcnZpY2UiLCJtZWRpY2FsX3JlY29yZHNfc2VydmljZSIsImFwcG9pbnRtZW50X3NlcnZpY2UiXSwicm9sZSI6ImRvY3RvciJ9.RsYDszzMzdX3WarKP7z7VNrY-QprF-27ijsgZZlXe53Vc4YRF2WgVr5P05cuFcZ4l941UFrFPJvN4c7TY_YpLcbLfWoBTPuVpbmzesjyHg-ItmqNXlz_CyPIZMw9VRJIvQoBlZFKw3asP-OdPIkvpMPjhE0H8aCs4Euxpl3C3yB--573KpRY0f_ghagsIxg2Rr00qtC9F8diQnSuAEm127Hxi2b5zXOd7vld_qf6N0Ge_xAieEL-FYtXr8FTh6ovH4zFOOtdlV0tYPik-_pq9yeBNNiRxpmEeR_vjWf0noLmlrUoexJPeLUuxwHA1-JWgtH1jRilN2t1sPGQ0u8wpw

{
    "prognosis":"Non-Acid reflux",
    "patient_id":"0a20cc04-3330-410c-9e1c-8737328d5140",
    "tests":[
        {
            "name":"H-Pylori",
            "result":"Acte reflux of stomac acids and high hpv levels"
        }
    ]
}

###
GET http://127.0.0.1:8003/records/doctors/records/
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ0Mzc0ODY4LCJpYXQiOjE3NDQzNzEyNjgsImp0aSI6ImI2MmE1NTc3YWIxZTQ5MDI4ODM2ODRlMTRlYWFkOTgyIiwidXNlcl9pZCI6IjBmOGI0NGZjLWU3Y2ItNDAwZi04ZDVkLTI1ZTIwYTUxYzI3ZCIsImlzX3N1cGVydXNlciI6ZmFsc2UsImlzX3N0YWZmIjpmYWxzZSwiaXNfYWN0aXZlIjp0cnVlLCJpc3MiOiJkb2N0b3Jfc2VydmljZSIsImF1ZCI6WyJwYXRpZW50X3NlcnZpY2UiLCJtZWRpY2FsX3JlY29yZHNfc2VydmljZSIsImFwcG9pbnRtZW50X3NlcnZpY2UiXSwicm9sZSI6ImRvY3RvciJ9.FdcEZPTl5ZMA6DE66N9sZnHfMXEewhuysACKNkU3kA3z9wZbJgHXYxIlREH8islrI3XXdNvLzZgmCEyq4pnZI5pFNgNkhFodEW9IZ5AXQbH2fQehwhfqbHhu4bWSNy_pAHgxQGqDJpPyesDdCz5yitDaHK3F6WBOQta45-IxU7bMSWa7ly1psHZiQZI-aMnNa8F8_YStxOUiMFKnZypw1cxRRwg6M8W9v_-f7H07qCFxG7_6QfrNmHAfpjKtiN8ogdc52bsu0wivd7Xi65jL7G_4ps0saEuOMNlgmMoA-Q3CCu6xzj9WQqW0K629ud1nqIGn84Mb_fWQCgOOBCN7SQ


###
GET http://127.0.0.1:8003/records/patients/records/
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ0Mzg0OTY2LCJpYXQiOjE3NDQzODMxNjYsImp0aSI6ImZmYzcxZGIwNTQ3MzRlMWViZTVjNmM3NDIzMzA5NTNjIiwidXNlcl9pZCI6IjBhMjBjYzA0LTMzMzAtNDEwYy05ZTFjLTg3MzczMjhkNTE0MCIsImlzX3N1cGVydXNlciI6ZmFsc2UsImlzX3N0YWZmIjpmYWxzZSwiaXNfYWN0aXZlIjp0cnVlLCJpc3MiOiJwYXRpZW50X3NlcnZpY2UiLCJhdWQiOlsiYXBwb2ludG1lbnRfc2VydmljZSIsImRvY3Rvcl9zZXJ2aWNlIiwibWVkaWNhbF9yZWNvcmRzX3NlcnZpY2UiXSwicm9sZSI6InBhdGllbnQifQ.OYZPqJVNl7NOl-VyOlCH46DC20YRMjDD1QFOArhi6uTMIapkeem1hBWGewQAOJwH5VMSbhD11xOUAJLW_g8uqANa8KqlO2xMNz6Ao-QRXbOKq0CFWU-tppEeMtV73HITfkaFrlGu0qR-2sWAwmABLcI88nVdfKGlsBAoalDPbqrEl3Q5__vs0Y_8NuYsNe9TF0Avey1Feids8IEu3xWTE0NB5yoHvU_ct_RySBvapk2qd3qD9LiKAS5NM-cxMopCEED7a3bM3-Onkk-iGKE3OIQdI_BR2xXNH4ljTJexCRXuSAAOcHrAqZmOArw0I_iWV7Vkt6_zol3CCaLsJ2TFLA


###
GET http://127.0.0.1:8003/records/patient/0a20cc04-3330-410c-9e1c-8737328d5140/records/
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ0Mzg3MjQ3LCJpYXQiOjE3NDQzODM2NDcsImp0aSI6IjQwYWIyODY3ZmUxNTQ3ZWM5NDI4MTMwZjZjYjlhZDdlIiwidXNlcl9pZCI6IjBmOGI0NGZjLWU3Y2ItNDAwZi04ZDVkLTI1ZTIwYTUxYzI3ZCIsImlzX3N1cGVydXNlciI6ZmFsc2UsImlzX3N0YWZmIjpmYWxzZSwiaXNfYWN0aXZlIjp0cnVlLCJpc3MiOiJkb2N0b3Jfc2VydmljZSIsImF1ZCI6WyJwYXRpZW50X3NlcnZpY2UiLCJtZWRpY2FsX3JlY29yZHNfc2VydmljZSIsImFwcG9pbnRtZW50X3NlcnZpY2UiXSwicm9sZSI6ImRvY3RvciJ9.TE3lbN8XmgsIxhZo9CD5vWM-Ekom8jiA__GUhEc-KagVpX9rtzsNlZoCQzcerzVvCyIUvLzBcDXag5kJPUoEDVsNYe48bekiVzXB15_LAceylpEzO3hH7BI8eJ7oQT7yuHX2ItGeb0Z6NLrKDWSuJPM3jkejnjnxaQBvTiPnUYX0G599DjdMFkpGcRhgXK5_z2xwq9Y1X9LDy4LUqvGMu33pOvEZjWLOuV_pP-lOyXUaJ7RSFMJvqIWVxmBYcxp7Dlk5NQGpnKr271GSU72xVES25amjTl2DI_-n9z4aY84NB7-J3V78V_kcFA94LvE1AMuqwpzT1vvvXDQZndA9gg


###
GET http://127.0.0.1:8003/medical-records/5c0f69eb-40f1-47b9-a221-ea88c194684a/

###
PUT http://127.0.0.1:8003/medical-records/5c0f69eb-40f1-47b9-a221-ea88c194684a/
Content-Type: application/json

{
    "prognosis":"Severe Amoebic Dysentry",
    "tests":[
        {
            "name":"Stool Test",
            "result":"severe case of amoeba infestation in the stool"
        }
    ]
}

###
PUT http://127.0.0.1:8003/medical-records/test/aedab89b-f251-4a88-b430-6cfbce694f32/
Content-Type: application/json

{
    "name":"HEP Test",
    "result":"severe case of amoeba infestation in the stool"
}
