POST http://127.0.0.1:8003/records/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ1NTk0MjkxLCJpYXQiOjE3NDU1OTA2OTEsImp0aSI6IjAyMjg3ZWQ3MTdjZDQ2MDc5NjkwNzk4OTg0MGRjMWExIiwidXNlcl9pZCI6IjRmYTE2N2FjLTgzMDQtNGYyYS05M2M3LTViMmZkYzMyMDdjNyIsImlzX3N1cGVydXNlciI6ZmFsc2UsImlzX3N0YWZmIjpmYWxzZSwiaXNfYWN0aXZlIjp0cnVlLCJpc3MiOiJkb2N0b3Jfc2VydmljZSIsImF1ZCI6WyJwYXRpZW50X3NlcnZpY2UiLCJtZWRpY2FsX3JlY29yZHNfc2VydmljZSIsImFwcG9pbnRtZW50X3NlcnZpY2UiXSwicm9sZSI6ImRvY3RvciJ9.YY5SauGd7fC29bVKnF3Ky3d_6-yXLxnjD6GSeuvXIGlw76ikrwRV9gZgPW9pqzb7bd-YpoBfPD_9099NIkfXAPGLK_lvwdD2jlUS-qDpJQG7sjW8xOryNOkChAVmewzGwIT4ybLoot32FhxBH9qCfcef4yMHV2R0-goIsf93snWdu5kx8sWGfeNF770iQabNz2vU5xpitVn9TFjmZzGu9l2lUvjKd1amANSWgQKB4FNMKls1QeVghbaIgPpZnDRVoQ4OeM9PG02E6FKsO_gr_MajKlFOXvWcJtwVoyCuhloeCu2VXVUw6XUrxfHltyDX-oa_ewUNjvLzNrS1uRhp-A

{
    "systolic_bp": 55,
    "diastolic_bp":125,
    "body_temperature":47,
    "blood_group":7,
    "age":2,
    "height_cm": 50,
    "weight_kg": 5.5,
    "hiv_status":0, 
    "prognosis":"Acute rhinitis",
    "patient_id":"0374b291-d845-4935-a37d-86dd88543218",
    "tests":[
        {
            "name":"H-Pylori",
            "result":"Acte reflux of stomac acids and high hpv levels"
        }
    ]
}

###
GET http://127.0.0.1:8003/records/doctors/records/
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ1NTk0MjkxLCJpYXQiOjE3NDU1OTA2OTEsImp0aSI6IjAyMjg3ZWQ3MTdjZDQ2MDc5NjkwNzk4OTg0MGRjMWExIiwidXNlcl9pZCI6IjRmYTE2N2FjLTgzMDQtNGYyYS05M2M3LTViMmZkYzMyMDdjNyIsImlzX3N1cGVydXNlciI6ZmFsc2UsImlzX3N0YWZmIjpmYWxzZSwiaXNfYWN0aXZlIjp0cnVlLCJpc3MiOiJkb2N0b3Jfc2VydmljZSIsImF1ZCI6WyJwYXRpZW50X3NlcnZpY2UiLCJtZWRpY2FsX3JlY29yZHNfc2VydmljZSIsImFwcG9pbnRtZW50X3NlcnZpY2UiXSwicm9sZSI6ImRvY3RvciJ9.YY5SauGd7fC29bVKnF3Ky3d_6-yXLxnjD6GSeuvXIGlw76ikrwRV9gZgPW9pqzb7bd-YpoBfPD_9099NIkfXAPGLK_lvwdD2jlUS-qDpJQG7sjW8xOryNOkChAVmewzGwIT4ybLoot32FhxBH9qCfcef4yMHV2R0-goIsf93snWdu5kx8sWGfeNF770iQabNz2vU5xpitVn9TFjmZzGu9l2lUvjKd1amANSWgQKB4FNMKls1QeVghbaIgPpZnDRVoQ4OeM9PG02E6FKsO_gr_MajKlFOXvWcJtwVoyCuhloeCu2VXVUw6XUrxfHltyDX-oa_ewUNjvLzNrS1uRhp-A


###
GET http://127.0.0.1:8003/records/patients/records/
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ1NTg0NzkyLCJpYXQiOjE3NDU1ODI5OTIsImp0aSI6IjY5MGU4NzgwZTc0MjQyMDA5NjdiYzdkNzZlOWQ2YjljIiwidXNlcl9pZCI6IjAzNzRiMjkxLWQ4NDUtNDkzNS1hMzdkLTg2ZGQ4ODU0MzIxOCIsImlzX3N1cGVydXNlciI6ZmFsc2UsImlzX3N0YWZmIjpmYWxzZSwiaXNfYWN0aXZlIjp0cnVlLCJpc3MiOiJwYXRpZW50X3NlcnZpY2UiLCJhdWQiOlsiYXBwb2ludG1lbnRfc2VydmljZSIsImRvY3Rvcl9zZXJ2aWNlIiwibWVkaWNhbF9yZWNvcmRzX3NlcnZpY2UiXSwicm9sZSI6InBhdGllbnQifQ.SVcZ-ktiPs4EfnGSenIRcPTtTdc_tXtV_SrNbiIaN7az9o7WYjPDGxHU4B4tI1eJ1GVFC-SwsT66GdYaq6LJJ-j81O1E1OrLGZN32JfRT4yoILExgQtCAKCK1v_v6t8W4pWwSIb6FhciGCJ9msNJ3nXr6lfimsjHgLPMDt_xXuY1AeVn1nEBGdClmqYmesBLgivi1C9DcaqJv9ydTO8qkxvDm3HiMq6j4xK2w5JFhc4iZqPJm-buhD7ijehF-I5WmLLe30pH35YqiwuTDZeVldLsPUK_qlH37yaiemt3Tf0sCwstZrGd6XXGFEYbp7ARljq1dRqHKbQBmdoLIPtthA

0374b291-d845-4935-a37d-86dd88543218
###
GET http://127.0.0.1:8003/records/patient/0374b291-d845-4935-a37d-86dd88543218/records/
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ1NTg2NzE4LCJpYXQiOjE3NDU1ODMxMTgsImp0aSI6IjY0YWNhNjBiMGM5MzRhZTFhNzNkMWU0NWRmNjUwMjVlIiwidXNlcl9pZCI6IjRmYTE2N2FjLTgzMDQtNGYyYS05M2M3LTViMmZkYzMyMDdjNyIsImlzX3N1cGVydXNlciI6ZmFsc2UsImlzX3N0YWZmIjpmYWxzZSwiaXNfYWN0aXZlIjp0cnVlLCJpc3MiOiJkb2N0b3Jfc2VydmljZSIsImF1ZCI6WyJwYXRpZW50X3NlcnZpY2UiLCJtZWRpY2FsX3JlY29yZHNfc2VydmljZSIsImFwcG9pbnRtZW50X3NlcnZpY2UiXSwicm9sZSI6ImRvY3RvciJ9.lpONErQy2OY314hXP1QH39qlTYBO-EGuW7mr4V68BzxBxZPXN1LbroSsR6vL6U0mECzYrp-OBpUrFAcUKE5drVstVUjeHF5BR_5X69ytF12i4kZMOFvLsf1Q2imXLYjOZd87U804bNxS2zB432PysYdoNvm_JsrdZV3AvPW5QBEqg0Qx7mU3bioIfgWEEPVJFYRlNEGdO5Pl-WDFov8JdWfcBQ82Nbt-d8FZwBR98smpkOB45eobZU__6puHxxsJNLYHLeW4shXl4Z8Y7w0czVK05pC36Ug0vZTV5ku7hxUjaCtBGJue-rc6cKG_3HqIwssEC7XciORbF5a7MRE2-g


###
DELETE http://127.0.0.1:8003/records/6d3e9284-6245-4dd9-8218-53754b133638/delete/
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ1NTk0MjkxLCJpYXQiOjE3NDU1OTA2OTEsImp0aSI6IjAyMjg3ZWQ3MTdjZDQ2MDc5NjkwNzk4OTg0MGRjMWExIiwidXNlcl9pZCI6IjRmYTE2N2FjLTgzMDQtNGYyYS05M2M3LTViMmZkYzMyMDdjNyIsImlzX3N1cGVydXNlciI6ZmFsc2UsImlzX3N0YWZmIjpmYWxzZSwiaXNfYWN0aXZlIjp0cnVlLCJpc3MiOiJkb2N0b3Jfc2VydmljZSIsImF1ZCI6WyJwYXRpZW50X3NlcnZpY2UiLCJtZWRpY2FsX3JlY29yZHNfc2VydmljZSIsImFwcG9pbnRtZW50X3NlcnZpY2UiXSwicm9sZSI6ImRvY3RvciJ9.YY5SauGd7fC29bVKnF3Ky3d_6-yXLxnjD6GSeuvXIGlw76ikrwRV9gZgPW9pqzb7bd-YpoBfPD_9099NIkfXAPGLK_lvwdD2jlUS-qDpJQG7sjW8xOryNOkChAVmewzGwIT4ybLoot32FhxBH9qCfcef4yMHV2R0-goIsf93snWdu5kx8sWGfeNF770iQabNz2vU5xpitVn9TFjmZzGu9l2lUvjKd1amANSWgQKB4FNMKls1QeVghbaIgPpZnDRVoQ4OeM9PG02E6FKsO_gr_MajKlFOXvWcJtwVoyCuhloeCu2VXVUw6XUrxfHltyDX-oa_ewUNjvLzNrS1uRhp-A

###
PUT http://127.0.0.1:8003/records/600877e8-11be-49bd-bc86-aba3e4991b6c/update/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ1NTkwMzM2LCJpYXQiOjE3NDU1ODY3MzYsImp0aSI6ImE4ODExY2RlZmJlMzRkZjhhZGY5ZTg3Y2I0M2E5YzhlIiwidXNlcl9pZCI6IjRmYTE2N2FjLTgzMDQtNGYyYS05M2M3LTViMmZkYzMyMDdjNyIsImlzX3N1cGVydXNlciI6ZmFsc2UsImlzX3N0YWZmIjpmYWxzZSwiaXNfYWN0aXZlIjp0cnVlLCJpc3MiOiJkb2N0b3Jfc2VydmljZSIsImF1ZCI6WyJwYXRpZW50X3NlcnZpY2UiLCJtZWRpY2FsX3JlY29yZHNfc2VydmljZSIsImFwcG9pbnRtZW50X3NlcnZpY2UiXSwicm9sZSI6ImRvY3RvciJ9.kT3o51okJYERFGK3SrMpke04rDndhukZHnAEfmR4mbNGnBw1R7cYGPpOIvj5eDinhvVSjxy_4u0OLc1HZhv_poNlgBfKz5Uq6W15Y5XGkUKZTDX4-gPZKm_43t2fZaPKMums-kxOezABBttlr_wbUpQoMtN6-RJHAGMxOk1e5wjNFVQ8kMB8PoxwYdPLQWXamH3QO55p2iGhqypkF4JxQJTNXWiQDbc7G_Ude7BwnppXXySShslqWyE7Upr8aFH1yfcOcCK_7h27hkEYQd6PrGeuMeD1NP7p6pRoV2ifo0IbyhDBOUYCgscGMqDmGOOSq_2yIDtsHzr4Ddy7kqRGqA

{
    "prognosis":"Acid reflux",
    "tests":[
        {
            "name":"Stool Test",
            "result":"severe case of amoeba infestation in the stool",
            "details":""
        }
    ]
}

###
DELETE  http://127.0.0.1:8003/records/test/312361e3-9f42-4b0d-a472-9cb75a634a8e/
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ1NTkwMzM2LCJpYXQiOjE3NDU1ODY3MzYsImp0aSI6ImE4ODExY2RlZmJlMzRkZjhhZGY5ZTg3Y2I0M2E5YzhlIiwidXNlcl9pZCI6IjRmYTE2N2FjLTgzMDQtNGYyYS05M2M3LTViMmZkYzMyMDdjNyIsImlzX3N1cGVydXNlciI6ZmFsc2UsImlzX3N0YWZmIjpmYWxzZSwiaXNfYWN0aXZlIjp0cnVlLCJpc3MiOiJkb2N0b3Jfc2VydmljZSIsImF1ZCI6WyJwYXRpZW50X3NlcnZpY2UiLCJtZWRpY2FsX3JlY29yZHNfc2VydmljZSIsImFwcG9pbnRtZW50X3NlcnZpY2UiXSwicm9sZSI6ImRvY3RvciJ9.kT3o51okJYERFGK3SrMpke04rDndhukZHnAEfmR4mbNGnBw1R7cYGPpOIvj5eDinhvVSjxy_4u0OLc1HZhv_poNlgBfKz5Uq6W15Y5XGkUKZTDX4-gPZKm_43t2fZaPKMums-kxOezABBttlr_wbUpQoMtN6-RJHAGMxOk1e5wjNFVQ8kMB8PoxwYdPLQWXamH3QO55p2iGhqypkF4JxQJTNXWiQDbc7G_Ude7BwnppXXySShslqWyE7Upr8aFH1yfcOcCK_7h27hkEYQd6PrGeuMeD1NP7p6pRoV2ifo0IbyhDBOUYCgscGMqDmGOOSq_2yIDtsHzr4Ddy7kqRGqA

###
PUT http://127.0.0.1:8003/records/test/3c906a57-33c9-499c-b584-369154848302/
Content-Type: application/json
Authorization: Token eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ1NTkwMzM2LCJpYXQiOjE3NDU1ODY3MzYsImp0aSI6ImE4ODExY2RlZmJlMzRkZjhhZGY5ZTg3Y2I0M2E5YzhlIiwidXNlcl9pZCI6IjRmYTE2N2FjLTgzMDQtNGYyYS05M2M3LTViMmZkYzMyMDdjNyIsImlzX3N1cGVydXNlciI6ZmFsc2UsImlzX3N0YWZmIjpmYWxzZSwiaXNfYWN0aXZlIjp0cnVlLCJpc3MiOiJkb2N0b3Jfc2VydmljZSIsImF1ZCI6WyJwYXRpZW50X3NlcnZpY2UiLCJtZWRpY2FsX3JlY29yZHNfc2VydmljZSIsImFwcG9pbnRtZW50X3NlcnZpY2UiXSwicm9sZSI6ImRvY3RvciJ9.kT3o51okJYERFGK3SrMpke04rDndhukZHnAEfmR4mbNGnBw1R7cYGPpOIvj5eDinhvVSjxy_4u0OLc1HZhv_poNlgBfKz5Uq6W15Y5XGkUKZTDX4-gPZKm_43t2fZaPKMums-kxOezABBttlr_wbUpQoMtN6-RJHAGMxOk1e5wjNFVQ8kMB8PoxwYdPLQWXamH3QO55p2iGhqypkF4JxQJTNXWiQDbc7G_Ude7BwnppXXySShslqWyE7Upr8aFH1yfcOcCK_7h27hkEYQd6PrGeuMeD1NP7p6pRoV2ifo0IbyhDBOUYCgscGMqDmGOOSq_2yIDtsHzr4Ddy7kqRGqA

{
    "name": "H-Pylori",
    "result": "Acte reflux of gastric acids and high hpv levels",
    "details": "The tests are extensive"
}
