# Generated by Django 5.1.7 on 2025-05-21 19:07

import app.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_patient_email_alter_patient_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dependent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField()),
                ('last_name', models.CharField()),
                ('surname', models.CharField()),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('dob', models.DateField(validators=[app.validators.DatesValidator.validate_dob])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Minor',
                'verbose_name_plural': 'Minors',
                'db_table': 'dependents',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Guardianship',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('relationship', models.CharField(choices=[('father', 'Father'), ('mother', 'Mother'), ('guardian', 'Guardian')], max_length=20)),
                ('is_chaperone', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dependent', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.dependent')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'guardianship',
                'verbose_name_plural': 'guardianships',
                'db_table': 'guardianships',
                'constraints': [models.UniqueConstraint(fields=('dependent', 'patient'), name='unique_guardian_assignment'), models.CheckConstraint(condition=models.Q(models.Q(('relationship', 'guardian'), _negated=True), ('is_chaperone', False), _connector='OR'), name='chaperone_must_be_parent')],
                'unique_together': {('dependent', 'relationship')},
            },
        ),
    ]
