# Generated by Django 5.1.7 on 2025-05-22 21:08

import app.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_dependent_guardianship'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dependent',
            name='dob',
        ),
        migrations.AddField(
            model_name='dependent',
            name='date_of_birth',
            field=models.DateField(default='2000-10-10', validators=[app.validators.DatesValidator.validate_dob]),
        ),
        migrations.AddField(
            model_name='dependent',
            name='phone',
            field=models.CharField(blank=True, null=True, unique=True),
        ),
    ]
