# Generated by Django 5.1.7 on 2025-05-23 09:22

import app.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_dependent_dob_dependent_date_of_birth_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='guardianship',
            name='unique_guardian_assignment',
        ),
        migrations.RenameField(
            model_name='guardianship',
            old_name='patient',
            new_name='guardian',
        ),
        migrations.AddField(
            model_name='dependent',
            name='gender',
            field=models.IntegerField(choices=[(0, 'male'), (1, 'female')], default=0),
        ),
        migrations.AlterField(
            model_name='dependent',
            name='date_of_birth',
            field=models.DateField(default='2000-10-10', validators=[app.validators.DatesValidator.validate_dob]),
        ),
        migrations.AddConstraint(
            model_name='guardianship',
            constraint=models.UniqueConstraint(fields=('dependent', 'guardian'), name='unique_guardian_assignment'),
        ),
    ]
