# Generated by Django 5.1.7 on 2025-03-30 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_surname_alter_user_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='surname',
            field=models.CharField(null=True),
        ),
    ]
