# Generated by Django 5.1.7 on 2025-03-30 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_first_name_alter_user_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.EmailField(default='briannjeri9@fmail.com', max_length=254, unique=True),
        ),
    ]
